/**
 * App-wide API/backend strings.
 * Locale is controlled by NEXT_PUBLIC_LOCALE env var.
 * Translations are in i18n/messages/<locale>/messages.json
 */
import { UIConstants } from "@courselit/common-models";
import { messages } from "../i18n";

const api = messages.api;

export const responses = {
    error: api.error ?? "Error",
    domain_missing: api.domain_missing ?? "Domain is missing",
    domain_doesnt_exist: api.domain_doesnt_exist ?? "Domain does not exist",
    domain_super_admin_email_missing: api.domain_super_admin_email_missing ?? "SUPER_ADMIN_EMAIL environment variable is not defined",
    not_valid_subscription: api.not_valid_subscription ?? "No valid subscription found",
    sign_in_mail_prefix: api.sign_in_mail_prefix ?? "Sign in to",
    sign_in_mail_body: api.sign_in_mail_body ?? "Click the following link to sign in.",
    sign_in_link_text: api.sign_in_link_text ?? "Sign in",
    past_date: api.past_date ?? "Date cannot be in the past",
    invalid_permission: api.invalid_permission ?? "Invalid permission",
    user_not_found: api.user_not_found ?? "User not found.",
    request_not_authenticated: api.request_not_authenticated ?? "Request not authenticated",
    content_cannot_be_null: api.content_cannot_be_null ?? "Content cannot be empty",
    media_id_cannot_be_null: api.media_id_cannot_be_null ?? "Media cannot be empty",
    item_not_found: api.item_not_found ?? "Item not found",
    drip_not_released: api.drip_not_released ?? "This section is not yet released for you",
    not_a_creator: api.not_a_creator ?? "You do not have rights to perform this action",
    course_not_empty: api.course_not_empty ?? "Delete all lessons before trying deleting the course",
    invalid_offset: api.invalid_offset ?? "Invalid offset",
    is_not_admin: api.is_not_admin ?? "Insufficient privileges",
    is_not_admin_or_creator: api.is_not_admin_or_creator ?? "Insufficient privileges",
    blog_description_empty: api.blog_description_empty ?? "Description field is required",
    cannot_convert_to_blog: api.cannot_convert_to_blog ?? "The course has lessons hence cannot be converted to a post",
    cost_not_provided: api.cost_not_provided ?? "Cost field is required",
    invalid_cost: api.invalid_cost ?? "Invalid cost",
    cannot_add_to_blogs: api.cannot_add_to_blogs ?? "Cannot add lessons to a blog post",
    file_is_required: api.file_is_required ?? "A file is required",
    error_in_moving_file: api.error_in_moving_file ?? "Error in moving file",
    success: api.success ?? "success",
    user_name_cant_be_null: api.user_name_cant_be_null ?? "Name cannot be null",
    action_not_allowed: api.action_not_allowed ?? "You do not have rights to perform this action",
    invalid_input: api.invalid_input ?? "Invalid input",
    payment_invalid_settings: api.payment_invalid_settings ?? "Payment configuration is invalid",
    payment_info_required: api.payment_info_required ?? "Add payment method before creating a paid plan",
    unrecognised_currency_code: api.unrecognised_currency_code ?? "Unrecognised currency code",
    only_admins_can_purchase: api.only_admins_can_purchase ?? "Only admins can purchase courses on behalf of others",
    course_already_purchased: api.course_already_purchased ?? "You have already purchased this item",
    payment_settings_invalid_suffix: api.payment_settings_invalid_suffix ?? "settings are invalid",
    invalid_course_id: api.invalid_course_id ?? "Invalid course ID",
    invalid_user_id: api.invalid_user_id ?? "Invalid user ID",
    payment_settings_invalid: api.payment_settings_invalid ?? "Payment method is not set up. Please contact site admin.",
    not_enrolled: api.not_enrolled ?? "You are not enrolled in the course",
    currency_iso_not_set: api.currency_iso_not_set ?? "Currency ISO code is not set. Please contact site admin.",
    payment_method_not_saved: api.payment_method_not_saved ?? "Set a payment method before setting its corresponding secret key",
    invalid_payment_method: api.invalid_payment_method ?? "Invalid payment method",
    invalid_theme: api.invalid_theme ?? "Invalid theme",
    theme_not_installed: api.theme_not_installed ?? "The theme is not installed",
    invalid_layout: api.invalid_layout ?? "Invalid layout",
    missing_mandatory_blocks: api.missing_mandatory_blocks ?? "Missing mandatory blocks",
    destination_dont_exist: api.destination_dont_exist ?? "Destination does not exist",
    page_exists: api.page_exists ?? "A page with the URL already exists",
    invalid_format: api.invalid_format ?? "Invalid format",
    no_thumbnail: api.no_thumbnail ?? "No thumbnail available",
    file_size_exceeded: api.file_size_exceeded ?? "File size exceeded",
    name_is_required: api.name_is_required ?? "Name is required",
    mimetype_is_required: api.mimetype_is_required ?? "Mimetype is required",
    existing_group: api.existing_group ?? "A group with that name exists",
    group_not_empty: api.group_not_empty ?? "This section has lessons. Delete them before proceeding",
    update_payment_method: api.update_payment_method ?? "You need to set up a payment method to create paid content.",
    school_title_not_set: api.school_title_not_set ?? "Give your school a title before setting payment info.",
    internal_error: api.internal_error ?? "An internal error occurred. Please try again.",
    presigned_url_failed: api.presigned_url_failed ?? "That did not work! Please go back and try again.",
    file_uploaded: api.file_uploaded ?? "The file is uploaded. Go back to see your media.",
    media_deleted: api.media_deleted ?? "The media is deleted. Go back to see your media.",
    invalid_access_type: api.invalid_access_type ?? "The access type can either be public or private.",
    answers_missing: api.answers_missing ?? "Answers are missing.",
    cannot_be_evaluated: api.cannot_be_evaluated ?? "This lesson cannot be evaluated.",
    need_to_pass: api.need_to_pass ?? "You need to pass this test in order to mark it completed.",
    no_correct_answer: api.no_correct_answer ?? "Every question needs to have at least one correct answer.",
    no_empty_option: api.no_empty_option ?? "Options without text are not allowed in questions.",
    medialit_apikey_notfound: api.medialit_apikey_notfound ?? "You need to configure MediaLit to upload files.",
    mail_already_sent: api.mail_already_sent ?? "The mail is already sent",
    mail_subject_length_exceeded: (api.mail_subject_length_exceeded ?? "Subject cannot be longer than {max} characters").replace("{max}", String(UIConstants.MAIL_SUBJECT_MAX_LENGTH)),
    mail_max_recipients_exceeded: (api.mail_max_recipients_exceeded ?? "Total number of recipients cannot exceed {max}").replace("{max}", String(UIConstants.MAIL_MAX_RECIPIENTS)),
    email_delivery_failed_for_all_recipients: api.email_delivery_failed_for_all_recipients ?? "Email delivery failed for all recipients",
    courses_cannot_be_downloaded: api.courses_cannot_be_downloaded ?? "A course cannot be offered as a download.",
    apikey_already_exists: api.apikey_already_exists ?? "Apikey with that name already exists",
    sequence_details_missing: api.sequence_details_missing ?? "The following settings are missing",
    invalid_emails_order: api.invalid_emails_order ?? "Invalid emails order",
    no_published_emails: api.no_published_emails ?? "No published emails",
    sequence_not_active: api.sequence_not_active ?? "Sequence not active",
    sequence_already_started: api.sequence_already_started ?? "Sequence already started",
    mailing_address_too_short: api.mailing_address_too_short ?? "Mailing address is too short",
    mandatory_tags_missing: api.mandatory_tags_missing ?? "Mandatory tags are missing",
    cannot_delete_last_email: api.cannot_delete_last_email ?? "Cannot delete the last email in the sequence",
    invalid_drip_email: api.invalid_drip_email ?? "Drip email needs a subject and a body",
    cannot_invite_to_unpublished_product: api.cannot_invite_to_unpublished_product ?? "Cannot invite customers to an unpublished product",
    rejection_reason_missing: api.rejection_reason_missing ?? "Rejection reason is missing",
    joining_reason_missing: api.joining_reason_missing ?? "Joining reason required",
    invalid_category: api.invalid_category ?? "Invalid category",
    community_exists: api.community_exists ?? "A community with the same name already exists",
    payment_plan_required: api.payment_plan_required ?? "Add a payment plan before performing this action",
    community_requires_payment: api.community_requires_payment ?? "Community requires payment",
    community_has_no_payment_plans: api.community_has_no_payment_plans ?? "Community has no payment plans",
    duplicate_payment_plan: api.duplicate_payment_plan ?? "A payment plan with the same type already exists",
    default_payment_plan_cannot_be_archived: api.default_payment_plan_cannot_be_archived ?? "Default payment plan cannot be archived",
    default_payment_plan_required: api.default_payment_plan_required ?? "Mark a payment plan as default before enabling the community",
    community_content_already_reported: api.community_content_already_reported ?? "Content already reported",
    profile_incomplete: api.profile_incomplete ?? "Complete your profile to perform this action",
    cannot_reject_member_with_active_subscription: api.cannot_reject_member_with_active_subscription ?? "Cannot reject a member with an active subscription",
    cannot_leave_community_last_moderator: api.cannot_leave_community_last_moderator ?? "Last manager cannot leave the community",
    cannot_delete_last_permission_user: api.cannot_delete_last_permission_user ?? "Cannot delete the last user with required permissions:",
    cannot_change_role_inactive_member: api.cannot_change_role_inactive_member ?? "Cannot change role of a member who is not active",
    cannot_change_role_last_moderator: api.cannot_change_role_last_moderator ?? "Cannot change role of the last moderator",
    cannot_delete_last_category: api.cannot_delete_last_category ?? "Cannot delete the last category",
    lead_magnet_invalid_settings: api.lead_magnet_invalid_settings ?? "Product must have exactly one free payment plan to enable lead magnet",
    certificate_invalid_settings: api.certificate_invalid_settings ?? "Certificate can only be enabled for courses",
    sso_provider_already_exists: api.sso_provider_already_exists ?? "A SSO provider with the same provider ID already exists",
    digital_download_no_files: api.digital_download_no_files ?? "This digital download is empty. Please contact the creator.",
    download_link_expired: api.download_link_expired ?? "The download link has expired",
    user_already_exists: api.user_already_exists ?? "The user already exists",
    unsubscribe_success: api.unsubscribe_success ?? "Sorry to see you go. You have been unsubscribed from our mailing list.",
    download_course_cannot_have_groups: api.download_course_cannot_have_groups ?? "Digital download cannot have sections",
    download_course_last_group_cannot_be_removed: api.download_course_last_group_cannot_be_removed ?? "Last section cannot be removed from a digital download",
    certificate_demo_course_id_required: api.certificate_demo_course_id_required ?? "CourseID is required for demo certificate",
    provider_not_configured: api.provider_not_configured ?? "Configure the provider before enabling",
    provider_invalid_configuration: api.provider_invalid_configuration ?? "Invalid provider configuration",
    page_id_already_exists: api.page_id_already_exists ?? "This URL slug is already in use. Please choose a different one.",
    currency_iso_code_required: api.currency_iso_code_required ?? "Currency ISO code is required. Examples: usd, inr, gbp etc.",
    currency_unit_required: api.currency_unit_required ?? "A currency symbol is required. Examples: $, ₹, £ etc.",
};

export const internal = {
    error_unrecognised_payment_method: api.error_unrecognised_payment_method ?? "Unrecognized payment method",
    error_payment_method_not_implemented: api.error_payment_method_not_implemented ?? "Not yet implemented",
    error_db_connection_failed: api.error_db_connection_failed ?? "Unable to establish a connection to the database.",
    error_env_var_undefined: api.error_env_var_undefined ?? "A required environment variable is not defined",
    app_running: api.app_running ?? "CourseLit server is running on",
    invalid_cloud_storage_settings: api.invalid_cloud_storage_settings ?? "Cloud storage settings are invalid",
    domain_not_specified: api.domain_not_specified ?? "Domain is not specified",
    default_group_name: api.default_group_name ?? "First section",
    default_email_broadcast_subject: api.default_email_broadcast_subject ?? "Untitled broadcast",
    default_email_sequence_subject: api.default_email_sequence_subject ?? "First email",
    default_email_sequence_name: api.default_email_sequence_name ?? "Untitled Sequence",
    joining_reason_creator: api.joining_reason_creator ?? "Joined as creator",
};
