#!/usr/bin/env python3
"""
Add scattered strings from page-blocks, components-library, and app components
to the i18n messages JSON files.
"""
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EN_FILE = os.path.join(BASE, "apps/web/i18n/messages/en/messages.json")
PT_FILE = os.path.join(BASE, "apps/web/i18n/messages/pt-BR/messages.json")

# Additional scattered strings organized by namespace
SCATTERED_EN = {
    "blocks": {
        # Banner
        "banner_email_label": "Email",
        "banner_email_placeholder": "Enter your email",
        "banner_get_free": "Get for free",
        "banner_buy_now": "Buy now",
        "banner_set_url": "Set a URL",
        "banner_join_community": "Join community",
        "banner_members": "members",
        "banner_error": "Error",
        "banner_email_success": "We have emailed you the content. Thank you!",
        "banner_email_error": "That didn't work! Please try again.",
        # Email Form
        "email_form_default_subtitle": "Sign up here to get the latest articles, news and updates.",
        "email_form_captcha_error": "Could not verify that you are a human.",
        "email_form_success": "Success",
        "email_form_error": "Error",
        "email_form_name_label": "Name",
        "email_form_name_placeholder": "Enter your name",
        "email_form_email_label": "Email",
        "email_form_email_placeholder": "Enter your email",
        "email_form_default_title": "Sign up for my newsletter",
        "email_form_default_btn": "Subscribe",
        "email_form_default_success": "Thanks for subscribing.",
        "email_form_default_error": "That didn't work! Please try again.",
        # Hero Admin
        "hero_default_title": "Hero section",
        "hero_admin_basic": "Basic",
        "hero_admin_title": "Title",
        "hero_admin_media": "Media",
        "hero_admin_youtube_link": "YouTube/Vimeo Link",
        "hero_admin_enter_video_link": "Enter the link to the video",
        "hero_admin_upload_media": "Upload media",
        "hero_admin_video_override": "This will be overridden if a YouTube/Vimeo link is provided.",
        "hero_admin_video_popup": "Play video in a pop-up",
        "hero_admin_primary_btn": "Primary button",
        "hero_admin_secondary_btn": "Secondary button",
        "hero_admin_btn_text": "Button Text",
        "hero_admin_btn_action": "Button Action",
        "hero_admin_design": "Design",
        "hero_admin_media_alignment": "Media alignment",
        "hero_admin_left": "Left",
        "hero_admin_right": "Right",
        "hero_admin_layout": "Layout",
        "hero_admin_normal": "Normal",
        "hero_admin_card": "Card",
        "hero_admin_content_alignment": "Content alignment",
        "hero_admin_center": "Center",
        "hero_admin_title_font_size": "Title font size",
        "hero_admin_desc_font_size": "Description font size",
        "hero_admin_media_border_radius": "Media border radius",
        "hero_admin_aspect_ratio": "Aspect ratio",
        "hero_admin_object_fit": "Object fit",
        "hero_admin_cover": "Cover",
        "hero_admin_contain": "Contain",
        "hero_admin_fill": "Fill",
        "hero_admin_none": "None",
        "hero_admin_scale_down": "Scale-down",
        "hero_admin_cta": "Calls to action",
        "hero_admin_advanced": "Advanced",
        # Header
        "header_login": "Login",
        "header_logout": "Logout",
        "header_dashboard": "Dashboard",
        "header_admin_show_github": "Show Github Stars",
        "header_admin_backdrop_blur": "Backdrop blur",
        "header_admin_show_login": "Show login button",
        "header_admin_label": "Label",
        "header_admin_show_as_btn": "Show as button",
        "header_admin_primary_control": "Primary control",
        # Content
        "content_default_title": "Curriculum",
        "content_admin_header": "Header",
        "content_admin_title": "Title",
        "content_admin_header_alignment": "Header alignment",
        "content_admin_left": "Left",
        "content_admin_center": "Center",
        "content_admin_design": "Design",
        "content_admin_advanced": "Advanced",
        "content_error": "Error",
        # Featured
        "featured_default_title": "Featured",
        "featured_admin_header": "Header",
        "featured_admin_title": "Title",
        "featured_admin_header_alignment": "Header alignment",
        "featured_admin_left": "Left",
        "featured_admin_center": "Center",
        "featured_admin_products": "Products",
        "featured_admin_select_product": "Select a product",
        "featured_admin_design": "Design",
        "featured_admin_advanced": "Advanced",
        # Pricing
        "pricing_default_title": "Pricing",
        "pricing_default_plan": "Plan",
        "pricing_features_placeholder": "Feature 1, Feature 2, Feature 3",
        "pricing_default_cta": "Buy now",
        "pricing_monthly": "Monthly",
        "pricing_yearly": "Yearly",
        "pricing_admin_header": "Header",
        "pricing_admin_title": "Title",
        "pricing_admin_show_switcher": "Show pricing switcher",
        "pricing_admin_monthly_caption": "Monthly price caption",
        "pricing_admin_yearly_caption": "Yearly price caption",
        "pricing_admin_plans": "Plans",
        "pricing_admin_untitled": "Untitled",
        "pricing_admin_design": "Design",
        "pricing_admin_header_alignment": "Header alignment",
        "pricing_admin_left": "Left",
        "pricing_admin_center": "Center",
        "pricing_admin_columns": "Number of columns",
        "pricing_admin_advanced": "Advanced",
        "pricing_admin_price": "Price",
        "pricing_admin_yearly_price": "Yearly price",
        "pricing_admin_features": "Features",
        "pricing_admin_label": "Label",
        "pricing_admin_href": "Href",
        "pricing_admin_href_yearly": "Href (Yearly)",
        "pricing_admin_delete": "Delete",
        "pricing_admin_go_back": "Go back",
        # FAQ
        "faq_admin_title": "Title",
        "faq_admin_delete": "Delete",
        "faq_admin_sure": "Sure?",
        "faq_admin_go_back": "Go back",
        # Media block
        "media_admin_media": "Media",
        "media_admin_enter_video_link": "Enter the link to the video",
        "media_admin_upload_media": "Upload media",
        "media_admin_video_popup": "Play video in a pop-up",
        "media_admin_aspect_ratio": "Aspect ratio",
        "media_admin_object_fit": "Object fit",
        "media_admin_cover": "Cover",
        "media_admin_contain": "Contain",
        "media_admin_fill": "Fill",
        "media_admin_none": "None",
        "media_admin_design": "Design",
        "media_admin_border_radius": "Media border radius",
        "media_admin_border": "Border",
        "media_admin_border_desc": "Media will have a border",
        "media_admin_advanced": "Advanced",
        # Grid
        "grid_admin_icon_inline": "Icon inline",
        "grid_admin_icon_style": "Icon style",
        "grid_admin_title": "Title",
        "grid_admin_media": "Media",
        "grid_admin_media_alignment": "Media alignment",
        "grid_admin_above_title": "Above title",
        "grid_admin_below_title": "Below title",
        "grid_admin_delete": "Delete",
        "grid_admin_go_back": "Go back",
        "grid_invalid_svg": "Invalid SVG",
        "grid_admin_height": "Height",
        "grid_admin_width": "Width",
        "grid_admin_border_width": "Border width",
        "grid_admin_border_radius": "Border radius",
        "grid_admin_border_style": "Border style",
        "grid_admin_solid": "Solid",
        "grid_admin_dashed": "Dashed",
        "grid_admin_dotted": "Dotted",
        "grid_admin_double": "Double",
        "grid_admin_none": "None",
        "grid_admin_icon_color": "Icon color",
        "grid_admin_bg_color": "Background color",
        "grid_admin_border_color": "Border color",
        # Marquee
        "marquee_admin_add_new": "Add new item",
        "marquee_admin_pause_hover": "Pause on hover",
        "marquee_admin_text": "Text",
        "marquee_admin_link": "Link",
        "marquee_admin_link_desc": "Optional link for the item",
        "marquee_admin_delete": "Delete",
        "marquee_admin_go_back": "Go back",
        # Embed
        "embed_admin_content": "Content",
        "embed_admin_type": "Type",
        "embed_admin_script": "Script",
        "embed_admin_design": "Design",
        "embed_admin_aspect_ratio": "Aspect ratio",
        "embed_admin_default": "Default",
        "embed_admin_height": "Height",
        "embed_admin_advanced": "Advanced",
        # Footer
        "footer_default_legal": "Legal",
        "footer_default_terms": "Terms of Use",
        "footer_default_privacy": "Privacy Policy",
        "footer_admin_link": "Link",
        "footer_admin_sections": "Sections",
        "footer_admin_section_header": "Section header",
        "footer_admin_design": "Design",
        "footer_admin_title_font_size": "Title font size",
        "footer_admin_socials": "Socials",
        "footer_admin_social_icons_size": "Social icons size",
    },
    "components": {
        # Pagination
        "pagination_previous": "Previous",
        "pagination_next": "Next",
        # Content Padding
        "content_width": "Content width",
        "content_width_desc": "Width of the actual content. Only affects desktop screens.",
        "vertical_padding": "Vertical padding",
        "vertical_padding_desc": "Space on the top and bottom of the content. Only affects desktop screens.",
        # CSS ID
        "css_id_desc": "Useful for creating in page links",
        # Media Selector
        "upload_failed": "Upload Failed",
        "upload_file_btn": "Upload file",
        "upload_file_title": "Upload File",
        "upload_drag_drop": "Drag and drop your file or click to browse",
        "upload_drop_here": "Drop file here or click",
        "upload_selected": "Selected:",
        "upload_caption": "Caption (optional)",
        "upload_caption_placeholder": "Add a caption to your file...",
        "upload_processing": "Processing...",
        "upload_cancel": "Cancel",
        "upload_btn": "Upload",
        "media_error": "Error",
        "media_working": "Working...",
        "media_remove": "Remove",
        # Select
        "select_placeholder": "Select a value",
    },
    "community": {
        "reported": "Reported",
        "content_reported": "Content has been reported",
        "error": "Error",
        "reply_placeholder": "Write a reply...",
        "delete_comment": "Delete comment",
        "report_comment": "Report comment",
        "report_reason_placeholder": "Reason for reporting...",
        "post_title_placeholder": "Title",
        "post_body_placeholder": "What's on your mind?",
        "select_category": "Select a category",
        "save": "Save",
        "post": "Post",
        "members": "members",
        "reason_to_join_placeholder": "Reason to join",
        "rejection_reason": "Rejection reason",
        "url_copied": "Page URL copied to clipboard!",
        "just_now": "Just now",
        "failed_update_post": "Failed to update post",
        "failed_add_post": "Failed to add post",
        "failed_delete_post": "Failed to delete post",
        "post_reported": "Post has been reported",
        "less": "Less",
        "more": "More...",
        "delete_post": "Delete Post",
        "report_post": "Report Post",
        "unpin": "Unpin",
        "pin": "Pin",
        "search_gifs": "Search GIFs",
        "loading_gifs": "Loading GIFs...",
        "add_comment_placeholder": "Add a comment...",
        "success": "Success",
        "subscription_copied": "Subscription ID is copied to clipboard",
        "filter_by_status": "Filter by status",
        "all": "All",
        "status": "Status",
        "role": "Role",
        "subscription": "Subscription",
        "change_status": "Change status",
        "change_role": "Change role",
        "reject_membership": "Reject Membership Request",
        "reason": "Reason",
        "reason_to_join": "Reason to join",
    },
    "checkout": {
        "select_plan": "Please select a plan",
        "error": "Error",
        "already_owned": "Already owned",
        "reason_for_joining": "Reason for joining",
        "reason_placeholder": "Please provide your reason for joining",
        "invalid_email": "Invalid email address",
        "valid_email": "Please enter a valid email address",
        "email_placeholder": "Email address",
        "otp_placeholder": "Enter OTP",
        "free_plan": "Free plan",
        "hide_order": "Hide",
        "show_order": "Show",
        "order_suffix": "order",
        "something_wrong": "Something went wrong",
        "course_not_found": "Course not found",
        "community_not_found": "Community not found",
    },
    "admin": {
        # Sidebar
        "overview": "Overview",
        "products": "Products",
        "communities": "Communities",
        "all_users": "All users",
        "tags": "Tags",
        "broadcasts": "Broadcasts",
        "sequences": "Sequences",
        "support": "Support",
        "create": "Create",
        # Products page
        "public": "Public",
        "hidden": "Hidden",
        "published": "Published",
        "draft": "Draft",
        "filter_by_status": "Filter by status",
        "all": "All",
        "create_course": "Create a course",
        "create_download": "Create a digital download",
        "create_community": "Create a community",
        # Overview
        "select_time_range": "Select time range",
        "sales": "Sales",
        "customers": "Customers",
        "new_community_members": "New community members",
        "subscribers": "Subscribers",
        # Community manage
        "community_deleted": "Community has been deleted successfully",
        "name": "Name",
        "community_name_placeholder": "Community name",
        "joining_reason_text": "Joining reason text",
        "joining_reason_placeholder": "Text to show when users request to join...",
        "save_changes": "Save Changes",
        "category_name_placeholder": "Enter category name",
        "delete_community": "Delete Community",
        "delete_type_confirm": "Type 'delete' to confirm",
        "cancel": "Cancel",
        "delete": "Delete",
        "delete_category": "Delete Category",
        "select_category": "Select a category",
        # Reports
        "pending": "Pending",
        "accepted": "Accepted",
        "rejected": "Rejected",
        "enter_rejection_reason": "Enter Rejection Reason",
        # Communities list
        "members": "Members",
        "actions": "Actions",
        "view_page": "View page",
        "settings": "Settings",
        # Get set up
        "customize_school": "Customize your school",
        "open_branding": "Open branding settings",
        "set_up_payment": "Set up payment",
        "open_payment": "Open payment settings",
        "edit_homepage": "Edit your homepage",
        "open_page_builder": "Open page builder",
        "create_first_product": "Create your first product",
        "create_publish_course": "Create a course and publish it to make it live.",
        # Product detail
        "share_product": "Share product",
        "downloads": "Downloads",
        "people_completed": "People who completed the course",
        # Support
        "documentation": "Documentation",
        "ask_discord": "Ask in Discord",
        "open_discord": "Open Discord",
        "found_bug": "Found a bug?",
        "post_issue": "Post an issue",
        # Payments
        "free": "Free",
        "one_time": "One time",
        "monthly": "Monthly",
        "yearly": "Yearly",
        "make_recommended": "Make recommended",
        "archive_plan": "Archive plan",
        "amount_negative": "Amount cannot be negative",
        "installments_negative": "Installments cannot be negative",
        "failed_create_plan": "Failed to create payment plan",
        "enter_plan_description": "Enter plan description",
        "select_plan_type": "Select a plan type",
        "one_time_amount": "One-time Amount",
        "enter_amount": "Enter amount",
        "enter_number": "Enter number",
        "subscription_type": "Subscription Type",
        "select_subscription_type": "Select subscription type",
        "monthly_amount": "Monthly Amount",
        "enter_monthly_amount": "Enter monthly amount",
        "yearly_amount": "Yearly Amount",
        "add_product": "Add Product",
        # Misc
        "no_theme_selected": "No theme selected",
        "no_content": "No content to display",
        "delete_segment": "Delete Segment",
        "no_api_keys": "No API keys found",
        "reset": "Reset",
        "school_settings": "School Settings",
        "active": "Active",
        "restricted": "Restricted",
        "users_breadcrumb": "Users",
        "failed_mark_read": "Failed to mark all as read",
        "failed_open_notification": "Failed to open the notification",
        # Editable widget
        "move_up": "Move up",
        "add_widget_below": "Add widget below",
        "move_down": "Move down",
    },
}

SCATTERED_PT = {
    "blocks": {
        "banner_email_label": "E-mail",
        "banner_email_placeholder": "Digite seu e-mail",
        "banner_get_free": "Obter grátis",
        "banner_buy_now": "Comprar agora",
        "banner_set_url": "Definir uma URL",
        "banner_join_community": "Entrar na comunidade",
        "banner_members": "membros",
        "banner_error": "Erro",
        "banner_email_success": "Enviamos o conteúdo por e-mail. Obrigado!",
        "banner_email_error": "Não funcionou! Tente novamente.",
        "email_form_default_subtitle": "Inscreva-se para receber os últimos artigos, notícias e atualizações.",
        "email_form_captcha_error": "Não foi possível verificar que você é humano.",
        "email_form_success": "Sucesso",
        "email_form_error": "Erro",
        "email_form_name_label": "Nome",
        "email_form_name_placeholder": "Digite seu nome",
        "email_form_email_label": "E-mail",
        "email_form_email_placeholder": "Digite seu e-mail",
        "email_form_default_title": "Inscreva-se na minha newsletter",
        "email_form_default_btn": "Inscrever-se",
        "email_form_default_success": "Obrigado por se inscrever.",
        "email_form_default_error": "Não funcionou! Tente novamente.",
        "hero_default_title": "Seção principal",
        "hero_admin_basic": "Básico",
        "hero_admin_title": "Título",
        "hero_admin_media": "Mídia",
        "hero_admin_youtube_link": "Link YouTube/Vimeo",
        "hero_admin_enter_video_link": "Insira o link do vídeo",
        "hero_admin_upload_media": "Enviar mídia",
        "hero_admin_video_override": "Será substituído se um link YouTube/Vimeo for fornecido.",
        "hero_admin_video_popup": "Reproduzir vídeo em pop-up",
        "hero_admin_primary_btn": "Botão primário",
        "hero_admin_secondary_btn": "Botão secundário",
        "hero_admin_btn_text": "Texto do botão",
        "hero_admin_btn_action": "Ação do botão",
        "hero_admin_design": "Design",
        "hero_admin_media_alignment": "Alinhamento da mídia",
        "hero_admin_left": "Esquerda",
        "hero_admin_right": "Direita",
        "hero_admin_layout": "Layout",
        "hero_admin_normal": "Normal",
        "hero_admin_card": "Cartão",
        "hero_admin_content_alignment": "Alinhamento do conteúdo",
        "hero_admin_center": "Centro",
        "hero_admin_title_font_size": "Tamanho da fonte do título",
        "hero_admin_desc_font_size": "Tamanho da fonte da descrição",
        "hero_admin_media_border_radius": "Raio da borda da mídia",
        "hero_admin_aspect_ratio": "Proporção",
        "hero_admin_object_fit": "Ajuste do objeto",
        "hero_admin_cover": "Cobrir",
        "hero_admin_contain": "Conter",
        "hero_admin_fill": "Preencher",
        "hero_admin_none": "Nenhum",
        "hero_admin_scale_down": "Reduzir",
        "hero_admin_cta": "Chamadas para ação",
        "hero_admin_advanced": "Avançado",
        "header_login": "Entrar",
        "header_logout": "Sair",
        "header_dashboard": "Painel",
        "header_admin_show_github": "Mostrar estrelas do Github",
        "header_admin_backdrop_blur": "Desfoque de fundo",
        "header_admin_show_login": "Mostrar botão de login",
        "header_admin_label": "Rótulo",
        "header_admin_show_as_btn": "Mostrar como botão",
        "header_admin_primary_control": "Controle primário",
        "content_default_title": "Conteúdo programático",
        "content_admin_header": "Cabeçalho",
        "content_admin_title": "Título",
        "content_admin_header_alignment": "Alinhamento do cabeçalho",
        "content_admin_left": "Esquerda",
        "content_admin_center": "Centro",
        "content_admin_design": "Design",
        "content_admin_advanced": "Avançado",
        "content_error": "Erro",
        "featured_default_title": "Destaques",
        "featured_admin_header": "Cabeçalho",
        "featured_admin_title": "Título",
        "featured_admin_header_alignment": "Alinhamento do cabeçalho",
        "featured_admin_left": "Esquerda",
        "featured_admin_center": "Centro",
        "featured_admin_products": "Produtos",
        "featured_admin_select_product": "Selecione um produto",
        "featured_admin_design": "Design",
        "featured_admin_advanced": "Avançado",
        "pricing_default_title": "Preços",
        "pricing_default_plan": "Plano",
        "pricing_features_placeholder": "Recurso 1, Recurso 2, Recurso 3",
        "pricing_default_cta": "Comprar agora",
        "pricing_monthly": "Mensal",
        "pricing_yearly": "Anual",
        "pricing_admin_header": "Cabeçalho",
        "pricing_admin_title": "Título",
        "pricing_admin_show_switcher": "Mostrar seletor de preço",
        "pricing_admin_monthly_caption": "Título do preço mensal",
        "pricing_admin_yearly_caption": "Título do preço anual",
        "pricing_admin_plans": "Planos",
        "pricing_admin_untitled": "Sem título",
        "pricing_admin_design": "Design",
        "pricing_admin_header_alignment": "Alinhamento do cabeçalho",
        "pricing_admin_left": "Esquerda",
        "pricing_admin_center": "Centro",
        "pricing_admin_columns": "Número de colunas",
        "pricing_admin_advanced": "Avançado",
        "pricing_admin_price": "Preço",
        "pricing_admin_yearly_price": "Preço anual",
        "pricing_admin_features": "Recursos",
        "pricing_admin_label": "Rótulo",
        "pricing_admin_href": "Link",
        "pricing_admin_href_yearly": "Link (Anual)",
        "pricing_admin_delete": "Excluir",
        "pricing_admin_go_back": "Voltar",
        "faq_admin_title": "Título",
        "faq_admin_delete": "Excluir",
        "faq_admin_sure": "Tem certeza?",
        "faq_admin_go_back": "Voltar",
        "media_admin_media": "Mídia",
        "media_admin_enter_video_link": "Insira o link do vídeo",
        "media_admin_upload_media": "Enviar mídia",
        "media_admin_video_popup": "Reproduzir vídeo em pop-up",
        "media_admin_aspect_ratio": "Proporção",
        "media_admin_object_fit": "Ajuste do objeto",
        "media_admin_cover": "Cobrir",
        "media_admin_contain": "Conter",
        "media_admin_fill": "Preencher",
        "media_admin_none": "Nenhum",
        "media_admin_design": "Design",
        "media_admin_border_radius": "Raio da borda da mídia",
        "media_admin_border": "Borda",
        "media_admin_border_desc": "A mídia terá uma borda",
        "media_admin_advanced": "Avançado",
        "grid_admin_icon_inline": "Ícone em linha",
        "grid_admin_icon_style": "Estilo do ícone",
        "grid_admin_title": "Título",
        "grid_admin_media": "Mídia",
        "grid_admin_media_alignment": "Alinhamento da mídia",
        "grid_admin_above_title": "Acima do título",
        "grid_admin_below_title": "Abaixo do título",
        "grid_admin_delete": "Excluir",
        "grid_admin_go_back": "Voltar",
        "grid_invalid_svg": "SVG inválido",
        "grid_admin_height": "Altura",
        "grid_admin_width": "Largura",
        "grid_admin_border_width": "Largura da borda",
        "grid_admin_border_radius": "Raio da borda",
        "grid_admin_border_style": "Estilo da borda",
        "grid_admin_solid": "Sólido",
        "grid_admin_dashed": "Tracejado",
        "grid_admin_dotted": "Pontilhado",
        "grid_admin_double": "Duplo",
        "grid_admin_none": "Nenhum",
        "grid_admin_icon_color": "Cor do ícone",
        "grid_admin_bg_color": "Cor de fundo",
        "grid_admin_border_color": "Cor da borda",
        "marquee_admin_add_new": "Adicionar novo item",
        "marquee_admin_pause_hover": "Pausar ao passar o mouse",
        "marquee_admin_text": "Texto",
        "marquee_admin_link": "Link",
        "marquee_admin_link_desc": "Link opcional para o item",
        "marquee_admin_delete": "Excluir",
        "marquee_admin_go_back": "Voltar",
        "embed_admin_content": "Conteúdo",
        "embed_admin_type": "Tipo",
        "embed_admin_script": "Script",
        "embed_admin_design": "Design",
        "embed_admin_aspect_ratio": "Proporção",
        "embed_admin_default": "Padrão",
        "embed_admin_height": "Altura",
        "embed_admin_advanced": "Avançado",
        "footer_default_legal": "Legal",
        "footer_default_terms": "Termos de Uso",
        "footer_default_privacy": "Política de Privacidade",
        "footer_admin_link": "Link",
        "footer_admin_sections": "Seções",
        "footer_admin_section_header": "Título da seção",
        "footer_admin_design": "Design",
        "footer_admin_title_font_size": "Tamanho da fonte do título",
        "footer_admin_socials": "Redes sociais",
        "footer_admin_social_icons_size": "Tamanho dos ícones sociais",
    },
    "components": {
        "pagination_previous": "Anterior",
        "pagination_next": "Próximo",
        "content_width": "Largura do conteúdo",
        "content_width_desc": "Largura do conteúdo. Afeta apenas telas desktop.",
        "vertical_padding": "Espaçamento vertical",
        "vertical_padding_desc": "Espaço acima e abaixo do conteúdo. Afeta apenas telas desktop.",
        "css_id_desc": "Útil para criar links dentro da página",
        "upload_failed": "Falha no envio",
        "upload_file_btn": "Enviar arquivo",
        "upload_file_title": "Enviar Arquivo",
        "upload_drag_drop": "Arraste e solte o arquivo ou clique para procurar",
        "upload_drop_here": "Solte o arquivo aqui ou clique",
        "upload_selected": "Selecionado:",
        "upload_caption": "Legenda (opcional)",
        "upload_caption_placeholder": "Adicione uma legenda ao seu arquivo...",
        "upload_processing": "Processando...",
        "upload_cancel": "Cancelar",
        "upload_btn": "Enviar",
        "media_error": "Erro",
        "media_working": "Processando...",
        "media_remove": "Remover",
        "select_placeholder": "Selecione um valor",
    },
    "community": {
        "reported": "Reportado",
        "content_reported": "O conteúdo foi reportado",
        "error": "Erro",
        "reply_placeholder": "Escreva uma resposta...",
        "delete_comment": "Excluir comentário",
        "report_comment": "Reportar comentário",
        "report_reason_placeholder": "Motivo da denúncia...",
        "post_title_placeholder": "Título",
        "post_body_placeholder": "O que você está pensando?",
        "select_category": "Selecione uma categoria",
        "save": "Salvar",
        "post": "Publicar",
        "members": "membros",
        "reason_to_join_placeholder": "Motivo para participar",
        "rejection_reason": "Motivo da rejeição",
        "url_copied": "URL da página copiada!",
        "just_now": "Agora mesmo",
        "failed_update_post": "Falha ao atualizar publicação",
        "failed_add_post": "Falha ao adicionar publicação",
        "failed_delete_post": "Falha ao excluir publicação",
        "post_reported": "Publicação reportada",
        "less": "Menos",
        "more": "Mais...",
        "delete_post": "Excluir Publicação",
        "report_post": "Reportar Publicação",
        "unpin": "Desafixar",
        "pin": "Fixar",
        "search_gifs": "Buscar GIFs",
        "loading_gifs": "Carregando GIFs...",
        "add_comment_placeholder": "Adicione um comentário...",
        "success": "Sucesso",
        "subscription_copied": "ID da assinatura copiado",
        "filter_by_status": "Filtrar por status",
        "all": "Todos",
        "status": "Status",
        "role": "Função",
        "subscription": "Assinatura",
        "change_status": "Alterar status",
        "change_role": "Alterar função",
        "reject_membership": "Rejeitar Solicitação de Membro",
        "reason": "Motivo",
        "reason_to_join": "Motivo para participar",
    },
    "checkout": {
        "select_plan": "Por favor, selecione um plano",
        "error": "Erro",
        "already_owned": "Já adquirido",
        "reason_for_joining": "Motivo para entrar",
        "reason_placeholder": "Informe o motivo para entrar",
        "invalid_email": "Endereço de e-mail inválido",
        "valid_email": "Por favor, insira um e-mail válido",
        "email_placeholder": "Endereço de e-mail",
        "otp_placeholder": "Digite o código",
        "free_plan": "Plano gratuito",
        "hide_order": "Ocultar",
        "show_order": "Mostrar",
        "order_suffix": "pedido",
        "something_wrong": "Algo deu errado",
        "course_not_found": "Curso não encontrado",
        "community_not_found": "Comunidade não encontrada",
    },
    "admin": {
        "overview": "Visão geral",
        "products": "Produtos",
        "communities": "Comunidades",
        "all_users": "Todos os usuários",
        "tags": "Tags",
        "broadcasts": "Transmissões",
        "sequences": "Sequências",
        "support": "Suporte",
        "create": "Criar",
        "public": "Público",
        "hidden": "Oculto",
        "published": "Publicado",
        "draft": "Rascunho",
        "filter_by_status": "Filtrar por status",
        "all": "Todos",
        "create_course": "Criar um curso",
        "create_download": "Criar um download digital",
        "create_community": "Criar uma comunidade",
        "select_time_range": "Selecione o período",
        "sales": "Vendas",
        "customers": "Clientes",
        "new_community_members": "Novos membros da comunidade",
        "subscribers": "Assinantes",
        "community_deleted": "Comunidade excluída com sucesso",
        "name": "Nome",
        "community_name_placeholder": "Nome da comunidade",
        "joining_reason_text": "Texto do motivo para entrar",
        "joining_reason_placeholder": "Texto exibido quando usuários pedem para entrar...",
        "save_changes": "Salvar Alterações",
        "category_name_placeholder": "Nome da categoria",
        "delete_community": "Excluir Comunidade",
        "delete_type_confirm": "Digite 'excluir' para confirmar",
        "cancel": "Cancelar",
        "delete": "Excluir",
        "delete_category": "Excluir Categoria",
        "select_category": "Selecione uma categoria",
        "pending": "Pendente",
        "accepted": "Aceito",
        "rejected": "Rejeitado",
        "enter_rejection_reason": "Insira o Motivo da Rejeição",
        "members": "Membros",
        "actions": "Ações",
        "view_page": "Ver página",
        "settings": "Configurações",
        "customize_school": "Personalize sua escola",
        "open_branding": "Abrir configurações de marca",
        "set_up_payment": "Configurar pagamento",
        "open_payment": "Abrir configurações de pagamento",
        "edit_homepage": "Editar sua página inicial",
        "open_page_builder": "Abrir construtor de páginas",
        "create_first_product": "Crie seu primeiro produto",
        "create_publish_course": "Crie um curso e publique-o para torná-lo ativo.",
        "share_product": "Compartilhar produto",
        "downloads": "Downloads",
        "people_completed": "Pessoas que concluíram o curso",
        "documentation": "Documentação",
        "ask_discord": "Pergunte no Discord",
        "open_discord": "Abrir Discord",
        "found_bug": "Encontrou um bug?",
        "post_issue": "Registrar problema",
        "free": "Grátis",
        "one_time": "Pagamento único",
        "monthly": "Mensal",
        "yearly": "Anual",
        "make_recommended": "Tornar recomendado",
        "archive_plan": "Arquivar plano",
        "amount_negative": "O valor não pode ser negativo",
        "installments_negative": "Parcelas não podem ser negativas",
        "failed_create_plan": "Falha ao criar plano de pagamento",
        "enter_plan_description": "Descrição do plano",
        "select_plan_type": "Selecione o tipo do plano",
        "one_time_amount": "Valor único",
        "enter_amount": "Insira o valor",
        "enter_number": "Insira o número",
        "subscription_type": "Tipo de assinatura",
        "select_subscription_type": "Selecione o tipo de assinatura",
        "monthly_amount": "Valor mensal",
        "enter_monthly_amount": "Insira o valor mensal",
        "yearly_amount": "Valor anual",
        "add_product": "Adicionar Produto",
        "no_theme_selected": "Nenhum tema selecionado",
        "no_content": "Nenhum conteúdo para exibir",
        "delete_segment": "Excluir Segmento",
        "no_api_keys": "Nenhuma chave API encontrada",
        "reset": "Redefinir",
        "school_settings": "Configurações da Escola",
        "active": "Ativo",
        "restricted": "Restrito",
        "users_breadcrumb": "Usuários",
        "failed_mark_read": "Falha ao marcar todas como lidas",
        "failed_open_notification": "Falha ao abrir a notificação",
        "move_up": "Mover para cima",
        "add_widget_below": "Adicionar widget abaixo",
        "move_down": "Mover para baixo",
    },
}


def main():
    # Load existing messages
    with open(EN_FILE, 'r', encoding='utf-8') as f:
        en_messages = json.load(f)
    with open(PT_FILE, 'r', encoding='utf-8') as f:
        pt_messages = json.load(f)

    # Add scattered strings
    for ns, strings in SCATTERED_EN.items():
        if ns not in en_messages:
            en_messages[ns] = {}
        en_messages[ns].update(strings)

    for ns, strings in SCATTERED_PT.items():
        if ns not in pt_messages:
            pt_messages[ns] = {}
        pt_messages[ns].update(strings)

    # Write back
    with open(EN_FILE, 'w', encoding='utf-8') as f:
        json.dump(en_messages, f, indent=2, ensure_ascii=False)
    with open(PT_FILE, 'w', encoding='utf-8') as f:
        json.dump(pt_messages, f, indent=2, ensure_ascii=False)

    # Also write to packages/i18n/src/messages/
    PKG_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "packages/i18n/src/messages")
    os.makedirs(os.path.join(PKG_DIR, "en"), exist_ok=True)
    os.makedirs(os.path.join(PKG_DIR, "pt-BR"), exist_ok=True)

    with open(os.path.join(PKG_DIR, "en/messages.json"), 'w', encoding='utf-8') as f:
        json.dump(en_messages, f, indent=2, ensure_ascii=False)
    with open(os.path.join(PKG_DIR, "pt-BR/messages.json"), 'w', encoding='utf-8') as f:
        json.dump(pt_messages, f, indent=2, ensure_ascii=False)

    # Stats
    total_new = sum(len(v) for v in SCATTERED_EN.values())
    total_all = sum(len(v) for v in en_messages.values())
    print(f"Added {total_new} scattered strings")
    print(f"Total strings in messages: {total_all}")
    for ns in en_messages:
        print(f"  {ns}: {len(en_messages[ns])}")


if __name__ == "__main__":
    main()
