#!/usr/bin/env python3
"""
Extract all exported string constants from CourseLit TypeScript files
and generate i18n JSON message files (en + pt-BR).
"""
import re
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UI_STRINGS = os.path.join(BASE, "apps/web/ui-config/strings.ts")
CONFIG_STRINGS = os.path.join(BASE, "apps/web/config/strings.ts")
MESSAGES_DIR = os.path.join(BASE, "apps/web/i18n/messages")

# Portuguese translations for all strings
PT_BR_TRANSLATIONS = {
    # ── ui-config/strings.ts ──────────────────────────────
    # Errors
    "ERR_ALL_FIELDS_REQUIRED": "Todos os campos são obrigatórios.",
    "ERR_PASSWORDS_DONT_MATCH": "As senhas não coincidem.",
    "SIGNUP_SUCCESS": "Cadastro realizado com sucesso. Faça login.",
    "ERR_COURSE_TITLE_REQUIRED": "Um título é obrigatório.",
    "ERR_COURSE_COST_REQUIRED": "O preço é obrigatório.",
    "RESP_API_USER_CREATED": "Usuário criado",

    # Placeholders
    "CREATOR_AREA_LINK_TEXT": "Criar",
    "CREATOR_AREA_PAGE_TITLE": "Painel",
    "GENERIC_TITLE": "Meu Site de Cursos",
    "GENERIC_SUBTITLE": "Aprenda novas habilidades",
    "GENERIC_SIGNIN_TEXT": "Entrar",
    "GENERIC_SIGNUP_TEXT": "Cadastrar",
    "GENERIC_SIGNOUT_TEXT": "Sair",

    # UI texts
    "BTN_LOAD_MORE": "Carregar mais",
    "MEDIA_UPLOAD_BUTTON_TEXT": "Enviar",
    "MEDIA_UPLOADING": "Enviando...",
    "MEDIA_ADD_NEW_BUTTON_TEXT": "Adicionar novo",
    "BUTTON_CANCEL_TEXT": "Cancelar",
    "BUTTON_CANCEL_SCHEDULED_MAIL": "Cancelar envio",
    "MEDIA_SEARCH_INPUT_PLACEHOLDER": "Pesquisar mídia",
    "LOAD_MORE_TEXT": "Carregar mais",
    "MANAGE_MEDIA_BUTTON_TEXT": "Inserir mídia",
    "MANAGE_COURSES_PAGE_HEADING": "Produtos",
    "COURSE_CUSTOMERS_PAGE_HEADING": "Clientes",
    "MANAGE_COMMUNITIES_PAGE_HEADING": "Comunidades",
    "MANAGE_PAGES_PAGE_HEADING": "Páginas",
    "BREADCRUMBS_EDIT_LESSON_COURSE_NAME": "Produto",
    "NEW_PAGE_HEADING": "Nova página",
    "USERS_MANAGER_PAGE_HEADING": "Usuários",
    "BTN_MANAGE_TAGS": "Gerenciar tags",
    "USERS_TAG_HEADER": "Tags",
    "USERS_TAG_NEW_HEADER": "Nova tag",
    "TAG_TABLE_HEADER_NAME": "Nome da tag",
    "BTN_NEW_TAG": "Nova tag",
    "TAG_TABLE_HEADER_SUBS_COUNT": "Contagem de usuários marcados",
    "TAGS_TABLE_CONTEXT_MENU_DELETE_PRODUCT": "Excluir tag",
    "TAGS_TABLE_CONTEXT_MENU_UNTAG": "Remover tag dos usuários",
    "UNTAG_POPUP_DESC": "Isso removerá a tag de todos os usuários marcados com ela. Os usuários permanecerão no sistema.",
    "UNTAG_POPUP_HEADER": "Remover tag dos usuários marcados com",
    "DELETE_TAG_POPUP_HEADER": "Excluir tag",
    "DELETE_TAG_POPUP_DESC": "Isso removerá a tag dos usuários marcados e excluirá a tag. Os usuários permanecerão no sistema.",
    "NEW_COURSE_PAGE_HEADING": "Adicionar curso",
    "EDIT_PRODUCT_HEADER": "Editar produto",
    "EDIT_BLOG": "Editar blog",
    "EDIT_EMAIL": "Editar email",
    "MEDIA_MANAGER_DIALOG_TITLE": "Adicionar mídia",
    "BUTTON_NEW_COURSE": "Novo",
    "BUTTON_DONE_TEXT": "Concluído",
    "DIALOG_TITLE_FEATURED_IMAGE": "Selecionar mídia",
    "BUTTON_SET_FEATURED_IMAGE": "Selecionar",
    "BUTTON_SELECT_MEDIA": "Escolher mídia",
    "FORM_FIELD_FEATURED_IMAGE": "Imagem de destaque",
    "BTN_DELETE_COURSE": "Excluir produto",
    "BTN_EXIT_COURSE": "Sair",
    "BTN_EXIT_COURSE_TOOLTIP": "Sair do curso",
    "BTN_TOGGLE_THEME": "Alternar tema",
    "BTN_ADD_VIDEO": "Adicionar",
    "ADD_VIDEO_DIALOG_TITLE": "Incorporar um vídeo online",
    "LABEL_NEW_PASSWORD": "Nova senha",
    "BUTTON_SAVE": "Salvar",
    "BUTTON_SAVING": "Salvando...",
    "GROUP_SETTINGS_HEADER": "Configurações",
    "GROUP_LESSONS_HEADER": "Aulas",
    "BUTTON_DELETE_GROUP": "Excluir Grupo",
    "BTN_RESET": "Redefinir",
    "SWITCH_ACCOUNT_ACTIVE": "Conta ativa",
    "LABEL_CONF_PASSWORD": "Confirmar senha",
    "HEADER_BLOG_POSTS_SECTION": "Blog",
    "HEADER_COURSES_SECTION": "Cursos",
    "HEADER_TAG_SECTION": "Conteúdo marcado com",
    "SITE_SETTINGS_TITLE": "Título",
    "SITE_SETTINGS_SUBTITLE": "Subtítulo",
    "SITE_SETTINGS_CURRENCY": "Moeda",
    "SITE_SETTINGS_LOGO": "Logo",
    "SITE_SETTINGS_DEFAULT_TITLE": "CourseLit",
    "SITE_SETTINGS_COURSELIT_BRANDING_CAPTION": "Remover marca CourseLit",
    "SITE_SETTINGS_COURSELIT_BRANDING_SUB_CAPTION": 'Ocultar "Desenvolvido por CourseLit" nos seus cursos e site CourseLit.',
    "SITE_SETTINGS_PAGE_HEADING": "Configurações",
    "HEADER_COURSELIT": "Sobre o CourseLit",
    "MEDIA_SELECTOR_UPLOAD_BTN_CAPTION": "Enviar uma imagem",
    "MEDIA_SELECTOR_REMOVE_BTN_CAPTION": "Remover imagem",
    "SITE_ADMIN_SETTINGS_STRIPE_SECRET": "Chave Secreta do Stripe",
    "SITE_ADMIN_SETTINGS_RAZORPAY_SECRET": "Chave Secreta do Razorpay",
    "SITE_ADMIN_SETTINGS_RAZORPAY_WEBHOOK_SECRET": "Webhook Secret do Razorpay",
    "SITE_ADMIN_SETTINGS_PAYPAL_SECRET": "Chave Secreta do PayPal",
    "SITE_ADMIN_SETTINGS_PAYTM_SECRET": "Chave Secreta do Paytm",
    "SITE_SETTINGS_SECTION_GENERAL": "Identidade Visual",
    "SITE_SETTINGS_SECTION_PAYMENT": "Pagamento",
    "SITE_SETTINGS_SECTION_MAILS": "E-mails",
    "SITE_ADMIN_SETTINGS_PAYMENT_METHOD": "Método de Pagamento",
    "SITE_SETTINGS_STRIPE_PUBLISHABLE_KEY_TEXT": "Chave Publicável do Stripe",
    "SITE_SETTINGS_RAZORPAY_KEY_TEXT": "Chave do Razorpay",
    "SITE_SETTINGS_LEMONSQUEEZY_KEY_TEXT": "Chave do Lemonsqueezy",
    "SITE_SETTINGS_LEMONSQUEEZY_STOREID_TEXT": "ID da Loja Lemonsqueezy",
    "SITE_SETTINGS_LEMONSQUEEZY_ONETIME_TEXT": "ID da variante pagamento único",
    "SITE_SETTINGS_LEMONSQUEEZY_SUB_MONTHLY_TEXT": "ID da variante assinatura (Mensal)",
    "SITE_SETTINGS_LEMONSQUEEZY_SUB_YEARLY_TEXT": "ID da variante assinatura (Anual)",
    "SITE_SETTINGS_PAYMENT_METHOD_NONE_LABEL": "Nenhum",
    "SITE_SETTINGS_PAYMENT_METHOD_RESET_BUTTON": "Redefinir",
    "SITE_SETTINGS_PAYMENT_METHOD_RESET_TOOLTIP": "Limpar o método de pagamento atual e manter as credenciais salvas do gateway",
    "SITE_SETTINGS_PAYMENT_METHOD_RESET_CONFIRM_TITLE": "Redefinir método de pagamento?",
    "SITE_SETTINGS_PAYMENT_METHOD_RESET_CONFIRM_DESCRIPTION": "Após a redefinição, todos os planos pagos de todos os produtos falharão no checkout com erro. Planos gratuitos continuarão funcionando.",
    "SITE_SETTINGS_PAYMENT_METHOD_RESET_CONFIRM_ACTION": "Redefinir",
    "FREE_COST": "GRÁTIS",
    "SIDEBAR_TEXT_COURSE_ABOUT": "Introdução",
    "REACT_COMPONENT_CRASHED": "Encontramos um problema ao exibir o conteúdo",
    "CHECKOUT_PAGE_TITLE": "Checkout",
    "PAYMENT_MODAL_PAYMENT_DETAILS_HEADER": "Detalhes do pagamento",
    "PAYMENT_MODAL_COST_PREFIX": "Valor",
    "PAYMENT_MODAL_PAY_NOW_BUTTON_CAPTION": "Pagar agora",
    "PAYMENT_INITIATION_FAILED": "O processamento do pagamento falhou. Feche este popup e tente novamente.",
    "PAYMENT_VERIFICATION_FAILED": "Não foi possível verificar seu pagamento. Por favor, tente novamente.",
    "STRIPE_PUBLISHABLE_KEY_EMPTY": "A configuração do Stripe está inválida. Por favor, contate o administrador.",
    "CAPTION_TRY_AGAIN": "Tentar novamente",
    "CAPTION_CLOSE": "Fechar",
    "LOADING": "Carregando",
    "WORKING": "Processando...",
    "BUTTON_NEW_LESSON_TEXT": "Adicionar Aula",
    "BUTTON_NEW_LESSON_TEXT_DOWNLOAD": "Adicionar Arquivo",
    "EDIT_LESSON_TEXT": "Editar Aula",
    "BUTTON_LESSON_DOWNLOAD": "Abrir em nova aba",
    "BUTTON_NEW_GROUP_TEXT": "Nova seção",
    "BUTTON_MANAGE_LESSONS_TEXT": "Gerenciar Aulas",
    "BUTTON_LESSON_VIEW_GO_BACK": "Voltar aos detalhes do curso",
    "BUTTON_DELETE_LESSON_TEXT": "Excluir",
    "COURSE_SETTINGS_CARD_HEADER": "Configurações",
    "DANGER_ZONE_HEADER": "Zona de perigo",
    "DANGER_ZONE_DESCRIPTION": "Esta ação é irreversível.",
    "DELETE_COURSE_POPUP_HEADER": "Excluir curso?",
    "POPUP_OK_ACTION": "Excluir",
    "POPUP_CANCEL_ACTION": "Cancelar",
    "BTN_BACK_TO_CONTENT": "Voltar ao conteúdo",
    "LOGIN_SECTION_HEADER": "Entrar",
    "LABEL_GROUP_NAME": "Nome",
    "LABEL_DRIP_EMAIL_SUBJECT": "Assunto",
    "LABEL_DRIP_DELAY": "Número de dias após o último envio",
    "LABEL_DRIP_DATE": "Data",
    "BTN_LOGIN": "Continuar",
    "BTN_LOGIN_NO_CODE": "Reenviar",
    "LOGIN_FORM_LABEL": "Digite seu email para entrar ou criar uma conta",
    "LOGIN_NO_CODE": "Não recebeu o código?",
    "BTN_LOGIN_GET_CODE": "Obter código",
    "LOGIN_CODE_INTIMATION_MESSAGE": "Digite o código enviado para seu email",
    "LOGIN_FORM_DISCLAIMER": "Ao enviar, você aceita os ",
    "SIGNUP_SECTION_HEADER": "Criar uma conta",
    "SIGNUP_SECTION_BUTTON": "Cadastrar",
    "MEDIA_MANAGER_PAGE_HEADING": "Mídia",
    "BUTTON_SEARCH": "Pesquisar",
    "BUTTON_ADD_FILE": "Selecionar um arquivo",
    "FILE_UPLOAD_SUCCESS": "Arquivo enviado",
    "HEADER_YOUR_MEDIA": "Sua mídia",
    "BLOG_POST_SWITCH": "Publicação",
    "DOWNLOADABLE_SWITCH": "Download",
    "TYPE_DROPDOWN": "Tipo",
    "LESSON_CONTENT_HEADER": "Conteúdo de Texto",
    "COURSE_CONTENT_HEADER": "Conteúdo",
    "LESSON_CONTENT_EMBED_HEADER": "Link",
    "LESSON_CONTENT_EMBED_PLACEHOLDER": "Um link para vídeo do YouTube etc.",
    "CONTENT_URL_LABEL": "Conteúdo de mídia",
    "MEDIA_MANAGER_YOUR_MEDIA_HEADER": "Sua mídia",
    "DIALOG_SELECT_BUTTON": "Selecionar",
    "LESSON_PREVIEW": "Prévia",
    "LESSON_PREVIEW_TOOLTIP": "Esta aula estará disponível gratuitamente para os usuários.",
    "LESSON_VISIBILITY": "Visibilidade",
    "LESSON_VISIBILITY_TOOLTIP": "Quando não publicada, esta aula fica oculta para alunos matriculados.",
    "DELETE_LESSON_POPUP_HEADER": "Excluir aula",
    "APP_MESSAGE_COURSE_DELETED": "Produto excluído",
    "APP_MESSAGE_LESSON_DELETED": "Aula excluída",
    "APP_MESSAGE_LESSON_SAVED": "Detalhes da aula salvos",
    "APP_MESSAGE_COURSE_SAVED": "Alterações salvas",
    "ENROLL_IN_THE_COURSE": "Você precisa estar matriculado no curso para ver esta aula.",
    "NOT_ENROLLED_HEADER": "Conteúdo Bloqueado",
    "USER_ERROR_HEADER": "Ops!",
    "ENROLL_BUTTON_TEXT": "Comprar agora",
    "CHECKOUT_BUTTON_TEXT": "Concluir Compra",
    "BUTTON_DELETE_MEDIA": "Excluir",
    "DELETE_MEDIA_POPUP_HEADER": "Excluir este arquivo?",
    "HEADER_EDITING_MEDIA": "Editar mídia",
    "MEDIA_EDITOR_HEADER_EDIT_DETAILS": "Detalhes",
    "HEADER_MEDIA_PREVIEW": "Prévia",
    "PREVIEW_PDF_FILE": "Visualizar em nova aba",
    "APP_MESSAGE_MEDIA_DELETED": "Mídia excluída",
    "APP_MESSAGE_MEDIA_UPDATED": "Detalhes da mídia atualizados",
    "PAGE_HEADER_ALL_COURSES": "Cursos",
    "PAGE_HEADER_ALL_POSTS": "Blog",
    "COURSE_TYPE_BLOG": "Blog",
    "BACK_TO_BLOG": "Voltar a todos os blogs",
    "COURSE_TYPE_COURSE": "Curso",
    "COURSE_CREATOR_PREFIX": "Por",
    "APP_MESSAGE_SETTINGS_SAVED": "Configurações salvas",
    "ENROLLED_COURSES_HEADER": "Cursos matriculados",
    "SITE_APIKEYS_SETTING_HEADER": "Chaves de API",
    "SITE_MAILS_HEADER": "E-mails",
    "BROADCASTS": "Transmissões",
    "SEQUENCES": "Sequências",
    "SITE_MAILING_ADDRESS_SETTING_HEADER": "Endereço de Correspondência",
    "SITE_MAILING_ADDRESS_SETTING_EXPLANATION": "Isso é necessário para cumprir a Lei CAN-SPAM.",
    "MAIL_REQUEST_RECEIVED": "Sua solicitação foi atualizada. Retornaremos em breve.",
    "MAIL_REQUEST_FORM_SUBMIT_INITIAL_REQUEST_TEXT": "Solicitar acesso",
    "MAIL_REQUEST_FORM_SUBMIT_UPDATE_REQUEST_TEXT": "Atualizar motivo",
    "SITE_CUSTOMISATIONS_SETTING_HEADER": "Injeção de Código",
    "SITE_MISCELLANEOUS_SETTING_HEADER": "Diversos",
    "ALPHA_LABEL": "Alfa",
    "BETA_LABEL": "Beta",
    "SITE_CUSTOMISATIONS_SETTING_CODEINJECTION_HEAD": "Injeção de código no <head>",
    "SITE_CUSTOMISATIONS_SETTING_CODEINJECTION_BODY": "Injeção de código no <body>",
    "DISCARD_COURSE_CHANGES_POPUP_HEADER": "Descartar alterações feitas no curso?",
    "FEATURED_SECTION_HEADER": "Recursos em Destaque",
    "CARD_HEADER_PAGE_LAYOUT": "Layout",
    "CARD_HEADER_THEME": "Temas",
    "CARD_DESCRIPTION_PAGE_LAYOUT": "Use os botões '+' para adicionar seus componentes favoritos às seções desejadas da página.",
    "ADD_COMPONENT_POPUP_HEADER": "Adicionar widgets",
    "APP_MESSAGE_CHANGES_SAVED": "Alterações salvas",
    "SUBHEADER_COURSES_SECTION": "Aprenda novas habilidades com nossos cursos cuidadosamente elaborados.",
    "SUBHEADER_FEATURED_SECTION": "Recursos selecionados pelos editores.",
    "SUBHEADER_THEME_ADD_THEME": "Novo tema",
    "SUBHEADER_THEME_ADDED_THEME": "Temas instalados",
    "SUBHEADER_THEME_ADD_THEME_INPUT_LABEL": "Editor de Tema",
    "SUBHEADER_THEME_ADD_THEME_INPUT_PLACEHOLDER": "Cole JSON válido aqui",
    "BUTTON_GET_THEMES": "Obter mais temas",
    "BUTTON_THEME_APPLY": "Aplicar",
    "BUTTON_THEME_UNINSTALL": "Desinstalar",
    "BUTTON_THEME_INSTALL": "Instalar",
    "BUTTON_THEME_REMIX": "Remixar",
    "DELETE_THEME_POPUP_HEADER": "Desinstalar tema",
    "APPLY_THEME_POPUP_HEADER": "Aplicar tema",
    "REMIXED_THEME_PREFIX": "Remix",
    "APP_MESSAGE_THEME_COPIED": "Tema pronto para editar",
    "NO_THEMES_INSTALLED": "Nenhum tema instalado",
    "APP_MESSAGE_THEME_INSTALLED": "Tema instalado",
    "APP_MESSAGE_THEME_APPLIED": "Tema aplicado",
    "APP_MESSAGE_THEME_UNINSTALLED": "Tema desinstalado",
    "HEADER_SECTION_PAYMENT_CONFIRMATION_WEBHOOK": "URLs de Webhook de Pagamento",
    "SUBHEADER_SECTION_PAYMENT_CONFIRMATION_WEBHOOK": "Seu processador de pagamento envia notificações sobre compras. O CourseLit precisa dessas notificações para refletir corretamente as compras dos usuários. Copie e cole nas configurações de webhook do seu processador de pagamento.",
    "PURCHASE_STATUS_PAGE_HEADER": "Status da Compra",
    "MAIN_MENU_ITEM_DASHBOARD": "Painel",
    "MAIN_MENU_ITEM_PROFILE": "Perfil",
    "MAIN_MENU_ITEM_NOTIFICATIONS": "Notificações",
    "LAYOUT_SECTION_MAIN_CONTENT": "Conteúdo Principal",
    "LAYOUT_SECTION_FOOTER_LEFT": "Seção Esquerda",
    "LAYOUT_SECTION_FOOTER_RIGHT": "Seção Direita",
    "LAYOUT_SECTION_TOP": "Topo",
    "LAYOUT_SECTION_FOOTER": "Rodapé",
    "LAYOUT_SECTION_BOTTOM": "Inferior",
    "LAYOUT_SECTION_ASIDE": "Lateral",
    "TRANSACTION_STATUS_SUCCESS": "Pagamento recebido.",
    "TRANSACTION_STATUS_SUCCESS_DETAILS": "Obrigado. Agora você pode ir ao seu curso e começar a aprender.",
    "TRANSACTION_STATUS_INITIATED": "Pagamento Ainda Não Confirmado.",
    "TRANSACTION_STATUS_FAILED": "Pagamento Falhou.",
    "TRANSACTION_STATUS_FAILED_DETAILS": "O provedor de serviço de pagamento não conseguiu processar seu pagamento. Volte e tente novamente.",
    "VISIT_COURSE_BUTTON": "Acessar curso",
    "VERIFY_PAYMENT_BUTTON": "Verificar Status do Pagamento",
    "PURCHASE_ID_HEADER": "ID da Compra",
    "PAGE_HEADER_FEATURED": "Conteúdo em Destaque",
    "BTN_VIEW_ALL": "Ver todos",
    "EMPTY_COURSES_LIST_ADMIN": "Crie seu primeiro curso clicando no botão + no canto superior direito.",
    "HEADER_RESET_PASSWORD": "Redefinir senha",
    "HEADER_DESIGN": "Site",
    "HEADER_YOUR_PROFILE": "Seu Perfil",
    "PROFILE_PAGE_MESSAGE_NOT_LOGGED_IN": "para ver seu perfil.",
    "PROFILE_PAGE_HEADER": "Perfil",
    "MY_CONTENT_HEADER": "Meu conteúdo",
    "NOTIFICATION_SETTINGS_PAGE_HEADER": "Notificações",
    "NOTIFICATION_SETTINGS_PAGE_DESCRIPTION": "Gerencie como você recebe notificações para cada atividade.",
    "NOTIFICATION_SETTINGS_RESOURCE_TEXT": "Personalizar notificações",
    "NOTIFICATION_SETTINGS_COLUMN_ACTIVITY": "Atividade",
    "NOTIFICATION_SETTINGS_EMPTY_STATE": "Nenhuma preferência de notificação disponível para sua conta.",
    "NOTIFICATION_SETTINGS_GROUP_GENERAL": "Geral",
    "NOTIFICATION_SETTINGS_GROUP_PRODUCT_MANAGEMENT": "Produto",
    "NOTIFICATION_SETTINGS_GROUP_USER_MANAGEMENT": "Usuário",
    "NOTIFICATION_SETTINGS_GROUP_COMMUNITY_MANAGEMENT": "Comunidade",
    "PROFILE_EMAIL_PREFERENCES": "Preferências de email",
    "PROFILE_SECTION_DETAILS": "Dados pessoais",
    "PROFILE_SECTION_DETAILS_NAME": "Nome",
    "PROFILE_SECTION_DETAILS_EMAIL": "Email",
    "PROFILE_SECTION_DETAILS_BIO": "Biografia",
    "PROFILE_SECTION_DISPLAY_PICTURE": "Foto de perfil",
    "PROFILE_EMAIL_PREFERENCES_NEWSLETTER_OPTION_TEXT": "Receber emails de newsletter e marketing",
    "BTN_PUBLISH": "Publicar",
    "BTN_UNPUBLISH": "Despublicar",
    "PERM_SECTION_HEADER": "Permissões",
    "USER_BASIC_DETAILS_HEADER": "Dados básicos",
    "USER_EMAIL_SUBHEADER": "Email",
    "USER_NAME_SUBHEADER": "Nome",
    "USER_FILTER_CLEAR": "Limpar filtros",
    "USER_FILTER_DROPDOWN_LABEL": "Adicionar filtro",
    "USER_FILTER_BTN_LABEL": "Filtros",
    "USER_FILTER_CATEGORY_EMAIL": "Email",
    "USER_FILTER_CATEGORY_PRODUCT": "Produto",
    "USER_FILTER_CATEGORY_COMMUNITY": "Comunidade",
    "USER_FILTER_CATEGORY_LAST_ACTIVE": "Último acesso",
    "USER_FILTER_CATEGORY_SIGNED_UP": "Cadastrado em",
    "USER_FILTER_CATEGORY_SUBSCRIPTION": "Assinatura",
    "USER_FILTER_CATEGORY_TAGGED": "Tag",
    "USER_FILTER_CATEGORY_PERMISSION": "Permissão",
    "USER_FILTER_EMAIL_IS_EXACTLY": "É exatamente",
    "USER_FILTER_EMAIL_CONTAINS": "Contém",
    "USER_FILTER_EMAIL_NOT_CONTAINS": "Não contém",
    "USER_FILTER_PRODUCT_HAS": "Possui",
    "USER_FILTER_PRODUCT_DOES_NOT_HAVE": "Não possui",
    "USER_FILTER_COMMUNITY_HAS": "Membro de",
    "USER_FILTER_COMMUNITY_DOES_NOT_HAVE": "Não é membro de",
    "USER_FILTER_APPLY_BTN": "Aplicar",
    "USER_FILTER_SAVE": "Salvar novo segmento",
    "USER_FILTER_SAVE_DESCRIPTION": "Você pode acessar os segmentos salvos no menu Segmentos",
    "USER_SEGMENT_DESCRIPTION": "Separe usuários em grupos distintos.",
    "USER_FILTER_LABEL_DEFAULT": "Todos",
    "USER_FILTER_AGGREGATOR_HEADER": "Combinar",
    "USER_FILTER_AGGREGATOR_ALL": "Todos",
    "USER_FILTER_AGGREGATOR_ANY": "Qualquer",
    "USER_FILTER_PRODUCT_DROPDOWN_LABEL": "Selecionar produto",
    "USER_FILTER_COMMUNITY_DROPDOWN_LABEL": "Selecionar comunidade",
    "USER_FILTER_TAGGED_DROPDOWN_LABEL": "Selecionar uma tag",
    "USER_FILTER_PERMISSION_DROPDOWN_LABEL": "Selecionar permissão",
    "USER_DELETE_SEGMENT": "Excluir Segmento",
    "USER_DELETE_SEGMENT_DESCRIPTION": "Tem certeza que deseja excluir ",
    "USER_FILTER_NEW_SEGMENT_NAME": "Nome do segmento",
    "USER_FILTER_SUBSCRIPTION_SUBSCRIBED": "Inscrito",
    "USER_FILTER_SUBSCRIPTION_NOT_SUBSCRIBED": "Não inscrito",
    "USER_FILTER_CHIP_TOOLTIP": "Remover filtro",
    "USER_FILTER_PERMISSION_HAS": "Possui",
    "USER_FILTER_PERMISSION_DOES_NOT_HAVE": "Não possui",
    "USER_FILTER_LAST_ACTIVE_BEFORE": "Antes de",
    "USER_FILTER_LAST_ACTIVE_AFTER": "Depois de",
    "USER_FILTER_LAST_ACTIVE_ON": "Em",
    "USER_FILTER_SIGNED_UP_BEFORE": "Antes de",
    "USER_FILTER_SIGNED_UP_AFTER": "Depois de",
    "USER_FILTER_SIGNED_UP_ON": "Em",
    "USER_FILTER_DATE_RANGE_DROPDOWN_LABEL": "Selecionar uma data",
    "DOCUMENTATION_LINK_LABEL": "Saiba mais",
    "PERM_COURSE_MANAGE": "Gerenciar produtos",
    "PERM_COURSE_MANAGE_ANY": "Gerenciar todos os produtos",
    "PERM_COURSE_PUBLISH": "Publicar conteúdo",
    "PERM_ENROLL_IN_COURSE": "Comprar produtos",
    "PERM_MEDIA_MANAGE": "Gerenciar arquivos",
    "PERM_MEDIA_MANAGE_ANY": "Gerenciar todos os arquivos",
    "PERM_SITE": "Gerenciar páginas",
    "PERM_SETTINGS": "Gerenciar configurações",
    "PERM_USERS": "Gerenciar usuários",
    "PERM_MANAGE_COMMUNITY": "Gerenciar comunidade",
    "MEDIA_EDITOR_ORIGINAL_FILE_NAME_HEADER": "Nome do Arquivo",
    "GROUP_LESSON_ITEM_UNTITLED": "Sem título",
    "SECTION_GROUP_HEADER": "Seções",
    "ERROR_SIGNIN_GENERATING_LINK": "Erro ao gerar link de login. Tente novamente.",
    "ERROR": "Parece que há um problema!",
    "SIGNIN_SUCCESS_PREFIX": "Um link de acesso foi enviado para",
    "ERROR_SIGNIN_VERIFYING_LINK": "Não foi possível fazer seu login. Por favor, tente novamente.",
    "COURSE_STRUCTURE_SELECT_LESSON": "Selecione uma aula na área de Seções.",
    "ERROR_GROUP_NEW_LESSON_WITHOUT_SAVE": "Salve as configurações da seção primeiro",
    "LABEL_GROUP_COLLAPSE": "Mostrar expandido",
    "SEARCH_TEXTBOX_PLACEHOLDER": "Pesquisar",
    "PAGE_TITLE_404": "Não encontrado",
    "MEDIA_PUBLIC": "Disponível publicamente",
    "MEDIA_DIRECT_URL": "URL Direta",
    "MEDIA_URL_COPIED": "Copiado para a área de transferência",
    "MEDIA_FILE_TYPE": "Tipo de arquivo",
    "LOGOUT": "Sair",
    "LOGOUT_MESSAGE": "Tem certeza que deseja sair?",
    "USER_TABLE_HEADER_NAME": "Detalhes",
    "USER_TABLE_HEADER_STATUS": "Status",
    "USER_TABLE_HEADER_PRODUCTS": "Produtos",
    "USER_TABLE_HEADER_COMMUNITIES": "Comunidades",
    "USER_TABLE_HEADER_JOINED": "Cadastrado em",
    "USER_TABLE_HEADER_LAST_ACTIVE": "Último acesso",
    "USER_TABLE_HEADER_EMAIL": "Email",
    "USER_TABLE_HEADER_NAME_NAME": "Nome",
    "USER_SEGMENT_DROPDOWN_LABEL": "Segmentos",
    "USER_TYPE_TOOLTIP": "Separe os usuários por funções. Usuários de audiência podem se matricular em cursos. Usuários de equipe têm direitos de administração.",
    "DIALOG_DONE_BUTTON": "Concluído",
    "DIALOG_EDIT_WIDGET_PREFIX": "Editar",
    "PRODUCTS_TABLE_HEADER_NAME": "Título",
    "PRODUCTS_TABLE_HEADER_TYPE": "Tipo",
    "PRODUCTS_TABLE_HEADER_STATUS": "Status",
    "PRODUCTS_TABLE_HEADER_STUDENTS": "Alunos",
    "PRODUCTS_TABLE_HEADER_SALES": "Vendas",
    "PRODUCTS_TABLE_HEADER_ACTIONS": "Ações",
    "PRODUCT_STATUS_DRAFT": "Rascunho",
    "PRODUCT_STATUS_PUBLISHED": "Publicado",
    "PRODUCT_TABLE_CONTEXT_MENU_DELETE_PRODUCT": "Excluir",
    "PRODUCT_TABLE_CONTEXT_MENU_EDIT_PAGE": "Editar página",
    "PRODUCT_TABLE_CONTEXT_MENU_INVITE_A_CUSTOMER": "Convidar um cliente",
    "BTN_INVITE": "Convidar",
    "BTN_GO_BACK": "Voltar",
    "BTN_NEW_PRODUCT": "Novo produto",
    "BTN_NEW_PAGE": "Nova página",
    "PAGE_HEADER_NEW_PRODUCT": "Novo Produto",
    "FORM_NEW_PRODUCT_TITLE": "Título",
    "FORM_NEW_PRODUCT_TYPE": "Tipo de produto",
    "FORM_NEW_PRODUCT_TITLE_PLC": "ex: 'Photoshop Para Iniciantes'",
    "FORM_NEW_PRODUCT_SELECT": "Tipo de produto",
    "BTN_CONTINUE": "Continuar",
    "DELETE_PRODUCT_POPUP_HEADER": "Excluir produto",
    "DELETE_PRODUCT_POPUP_TEXT": "Esta é uma ação irreversível e todos os dados e análises relacionados a este produto serão excluídos.",
    "FORM_NEW_PRODUCT_MENU_COURSE_SUBTITLE": "Um curso interativo com imagens, vídeos, texto e mais.",
    "FORM_NEW_PRODUCT_MENU_DOWNLOADS_SUBTITLE": "Um arquivo ZIP contendo imagens, vídeos, texto e mais.",
    "NEW_SECTION_HEADER": "Nova Seção",
    "EDIT_SECTION_DRIP": "Gotejamento",
    "DRIP_SECTION_STATUS": "Ativar Gotejamento",
    "EDIT_SECTION_HEADER": "Editar Seção",
    "DELETE_SECTION_HEADER": "Excluir seção",
    "PRICING_HEADER": "Preço",
    "PRICING_DROPDOWN": "Modelo de preço",
    "PRICING_FREE_SUBTITLE": "As pessoas podem acessar o conteúdo gratuitamente. O usuário precisa estar logado.",
    "PRICING_EMAIL_LABEL": "Entrega gratuita por email",
    "PRICING_EMAIL_SUBTITLE": "As pessoas receberão o conteúdo por email. O usuário não precisa estar logado.",
    "PRICING_PAID_LABEL": "Pago",
    "PRICING_FREE_LABEL": "Gratuito",
    "PAYMENT_PLAN_FREE_LABEL": "Gratuito",
    "PAYMENT_PLAN_ONETIME_LABEL": "Pagamento único",
    "PAYMENT_PLAN_SUBSCRIPTION_LABEL": "Assinatura",
    "PAYMENT_PLAN_EMI_LABEL": "Parcelado",
    "PRICING_PAID_SUBTITLE": "As pessoas podem acessar o conteúdo após um pagamento único. O usuário precisa estar logado.",
    "PRICING_PAID_NO_PAYMENT_METHOD": "Configure um método de pagamento nas Configurações para ativar esta opção.",
    "PUBLISH_TAB_STATUS_TITLE": "Status",
    "PUBLISH_TAB_STATUS_SUBTITLE": "Torne seu curso público ou privado.",
    "PUBLISH_TAB_VISIBILITY_TITLE": "Visibilidade",
    "PUBLISH_TAB_VISIBILITY_SUBTITLE": "O produto fica oculto e só pode ser acessado por URL direta.",
    "PAGE_TITLE_EDIT_PAGE": "Editar",
    "PAGE_TITLE_VIEW_PAGE": "Visualizar",
    "PAGE_HEADER_EDIT_PAGE": "Editar página",
    "EDIT_PAGE_MENU_ITEM": "Editar página",
    "VIEW_PAGE_MENU_ITEM": "Visualizar página",
    "EDIT_PAGE_BUTTON_UPDATE": "Publicar",
    "EDIT_PAGE_BUTTON_VIEW": "Visualizar",
    "EDIT_PAGE_BUTTON_DONE": "Sair",
    "EDIT_PAGE_ADD_WIDGET_TITLE": "Novo bloco",
    "EDIT_PAGE_WIDGET_LIST_HEADER": "Blocos da página",
    "THEMES_TABLE_HEADER_NAME": "Nome",
    "ACCOUNT_PROGRESS_SUFFIX": "% Completo",
    "CHECKOUT_PAGE_TOTAL": "Total",
    "COURSE_PROGRESS_PREV": "Anterior",
    "COURSE_PROGRESS_INTRO": "Introdução",
    "COURSE_PROGRESS_NEXT": "Completar e continuar",
    "COURSE_PROGRESS_START": "Iniciar",
    "COURSE_PROGRESS_FINISH": "Completar e finalizar",
    "BTN_NEW_BLOG": "Novo blog",
    "MANAGE_BLOG_PAGE_HEADING": "Blogs",
    "BLOG_TABLE_HEADER_NAME": "Título",
    "PAGE_HEADER_NEW_BLOG": "Novo blog",
    "MENU_BLOG_VISIT": "Visitar blog",
    "ACCOUNT_NO_PURCHASE_PLACEHOLDER": "Seus cursos matriculados aparecerão aqui.",
    "EXPORT_CSV": "Exportar para CSV",
    "GENERIC_FAILURE_MESSAGE": "Isso não funcionou. Por favor, tente novamente.",
    "LESSON_QUIZ_ADD_QUESTION": "Adicionar pergunta",
    "LESSON_QUIZ_ADD_OPTION_BTN": "Adicionar opção",
    "LESSON_QUIZ_CONTENT_HEADER": "Pergunta",
    "LESSON_QUIZ_OPTIONS_HEADER": "Opções",
    "LESSON_QUIZ_QUESTION_PLACEHOLDER": "Digite a pergunta aqui",
    "LESSON_QUIZ_OPTION_PLACEHOLDER": "Digite a opção aqui",
    "QUESTION_BUILDER_CORRECT_ANS_TOOLTIP": "Marcar como resposta correta",
    "QUESTION_BUILDER_EXPAND_TOOLTIP": "Expandir",
    "QUESTION_BUILDER_COLLAPSE_TOOLTIP": "Recolher",
    "LESSON_QUIZ_GRADED_TEXT": "Este quiz exige nota mínima para aprovação",
    "QUIZ_VIEWER_EVALUATE_BTN": "Enviar",
    "QUIZ_VIEWER_EVALUATE_BTN_LOADING": "Verificando...",
    "QUIZ_SCORE_PREFIX_MESSAGE": "Sua pontuação",
    "COURSE_STUDENT_REPORT_HEADER": "Alunos",
    "COURSE_STUDENT_TABLE_HEADER_PROGRESS": "Progresso",
    "COURSE_STUDENT_TABLE_HEADER_DOWNLOAD": "Baixado",
    "COURSE_STUDENT_TABLE_HEADER_SIGNED_UP_ON": "Matriculado em",
    "COURSE_STUDENT_TABLE_HEADER_LAST_ACCESSED_ON": "Último acesso",
    "COURSE_STUDENT_SEARCH_BY_TEXT": "Pesquisar aluno",
    "COURSE_STUDENT_NO_RECORDS": "Nenhum aluno encontrado",
    "QUESTION_BUILDER_DELETE_TOOLTIP": "Excluir pergunta",
    "PAGE_HEADER_EDIT_MAIL": "Compor email",
    "PAGE_HEADER_EDIT_SEQUENCE": "Detalhes da sequência",
    "BTN_SEND": "Enviar",
    "DIALOG_SEND_HEADER": "Enviar email",
    "BTN_SCHEDULE": "Agendar",
    "ERROR_SUBJECT_EMPTY": "O assunto não pode estar vazio",
    "ERROR_DELAY_EMPTY": "A data agendada não está no futuro",
    "FORM_MAIL_SCHEDULE_TIME_LABEL": "Enviar em",
    "BTN_SENDING": "Enviando",
    "MAIL_SUBJECT_PLACEHOLDER": "Assunto",
    "MAIL_PREVIEW_TITLE": "Texto de Prévia",
    "COMPOSE_SEQUENCE_FORM_TITLE": "Nome da sequência",
    "COMPOSE_SEQUENCE_ENTRANCE_CONDITION_DATA": "Dados da condição de entrada",
    "COMPOSE_SEQUENCE_FORM_FROM": "De",
    "COMPOSE_SEQUENCE_FROM_PLC": "João Silva",
    "COMPOSE_SEQUENCE_ENTRANCE_CONDITION": "Condição de entrada",
    "COMPOSE_SEQUENCE_EDIT_DELAY": "Atraso",
    "MAIL_TO_PLACEHOLDER": "Para",
    "MAIL_BODY_PLACEHOLDER": "Conteúdo do email",
    "PAGE_HEADER_ALL_MAILS": "E-mails",
    "SIDEBAR_MENU_MAILS": "E-mails",
    "SIDEBAR_MENU_USERS": "Usuários",
    "SIDEBAR_MENU_SETTINGS": "Configurações",
    "SIDEBAR_MENU_PAGES": "Páginas",
    "SIDEBAR_MENU_PRODUCTS": "Produtos",
    "SIDEBAR_MENU_DASHBOARD": "Início",
    "SIDEBAR_MENU_BLOGS": "Blogs",
    "PAGE_HEADER_EDIT_USER": "Editar usuário",
    "PAGE_HEADER_ALL_USER": "Todos os usuários",
    "TOAST_MAIL_SENT": "Email agendado para envio",
    "PAGE_PLACEHOLDER_MAIL": "Seus emails aparecerão aqui",
    "BTN_NEW_MAIL": "Nova transmissão",
    "BTN_NEW_SEQUENCE": "Nova sequência",
    "MAIL_TABLE_HEADER_SUBJECT": "Assunto",
    "MAIL_TABLE_HEADER_RECEPIENTS": "Nº de destinatários",
    "MAIL_SENDER_YOU": "Você",
    "MAIL_TABLE_HEADER_SENDER": "Remetente",
    "MAIL_TABLE_HEADER_STATUS": "Status",
    "MAIL_TABLE_HEADER_ENTRANTS": "Inscritos",
    "MAIL_TABLE_HEADER_SENT_ON": "Enviado em",
    "TOOLTIP_USER_PAGE_SEND_MAIL": "Enviar email para a seleção atual",
    "EDIT_PAGE_BUTTON_FONTS": "Fontes",
    "EDIT_PAGE_BUTTON_THEME": "Tema",
    "EDIT_PAGE_BUTTON_SEO": "SEO",
    "SEO_FORM_NAME_LABEL": "Título",
    "SEO_FORM_DESC_LABEL": "Descrição",
    "SEO_FORM_ROBOTS_LABEL": "Visibilidade nos motores de busca",
    "SEO_FORM_SOCIAL_IMAGE_LABEL": "Imagem do cartão social",
    "SEO_FORM_SOCIAL_IMAGE_TOOLTIP": "Ao compartilhar esta página nas redes sociais como Twitter ou Facebook, esta imagem será usada.",
    "EDIT_PAGE_SEO_HEADER": "SEO",
    "EDIT_PAGE_HEADER_ALL_PAGES": "Páginas",
    "LOGIN_SECTION_EMAIL_INVALID": "Email inválido",
    "COMPONENT_MISSING_SUFFIX": "componente não encontrado.",
    "LESSON_GROUP_DELETED": "Seção excluída",
    "USER_PERMISSION_AREA_SUBTEXT": "Controle quais ações este usuário pode realizar na sua escola.",
    "APIKEY_NEW_BUTTON": "Nova chave de API",
    "ADD_SSO_PROVIDER_BUTTON": "Novo provedor",
    "APIKEY_EXISTING_HEADER": "Chaves de API",
    "APIKEY_CARD_DESCRIPTION": "Usando chaves de API, você pode interagir com a API do CourseLit e criar integrações personalizadas",
    "SSO_CARD_DESCRIPTION": "Permita que seus usuários existentes façam login na sua escola",
    "SINGLE_SIGN_ON_HEADER": "Login Único (SSO)",
    "LOGIN_METHODS_HEADER": "Provedores de login",
    "LOGIN_METHODS_CARD_DESCRIPTION": "Controle como seus usuários acessam a escola",
    "APIKEY_EXISTING_TABLE_HEADER_CREATED": "Criado",
    "APIKEY_EXISTING_TABLE_HEADER_NAME": "Nome",
    "APIKEY_NEW_HEADER": "Nova chave de API",
    "SSO_PROVIDER_HEADER": "Provedor SSO",
    "SSO_PROVIDER_CARD_HEADER": "Configuração do IDP",
    "SSO_PROVIDER_CARD_DESCRIPTION": "Insira os valores do seu IDP (Okta, Azure AD, OneLogin, etc.)",
    "SSO_PROVIDER_SP_EMTPY": "Insira as configurações do seu IDP para ver estas configurações",
    "SSO_PROVIDER_SP_ACS_LABEL": "URL ACS SAML",
    "SSO_PROVIDER_SP_ENTITY_ID_LABEL": "URI de Audiência (SP Entity ID)",
    "APIKEY_NEW_LABEL": "Nome",
    "SSO_PROVIDER_DOMAIN_LABEL": "Domínio",
    "SSO_PROVIDER_ENTRY_POINT_LABEL": "Ponto de entrada",
    "SSO_PROVIDER_CERT_LABEL": "Certificado",
    "SSO_PROVIDER_CALLBACK_URL_LABEL": "URL de Callback",
    "SSO_PROVIDER_IDP_METADATA_LABEL": "Metadados do IDP",
    "SSO_PROVIDER_PROVIDER_ID_LABEL": "ID do Provedor",
    "SSO_PROVIDER_SUCCESS_MESSAGE": "Provedor SSO adicionado com sucesso",
    "PROVIDER_RESET_SUCCESS_MESSAGE": "Provedor redefinido com sucesso",
    "APIKEY_NEW_BTN_CAPTION": "Criar",
    "APIKEY_NEW_GENERATED_KEY_HEADER": "Sua nova chave de API",
    "APIKEY_NEW_GENERATED_KEY_DESC": "Copie e armazene com segurança. Você não poderá vê-la novamente.",
    "APIKEY_NEW_GENERATED_KEY_COPIED": "Copiado para a área de transferência",
    "APIKEY_REMOVE_BTN": "Remover",
    "SSO_PROVIDER_REMOVE_BTN": "Remover",
    "APIKEY_REMOVE_DIALOG_HEADER": "Remover Chave de API",
    "SSO_PROVIDER_REMOVE_DIALOG_HEADER": "Remover Provedor SSO",
    "SSO_PROVIDER_REMOVE_DIALOG_DESC": "Tem certeza que deseja remover este provedor?",
    "APIKEY_REMOVE_DIALOG_DESC": "Se você está usando esta chave na sua aplicação, removê-la quebrará a integração. Não há como desfazer a remoção.",
    "USER_TAGS_SUBHEADER": "Tags",
    "BTN_DELETE_USER": "Excluir usuário",
    "USER_DELETE_DIALOG_TITLE": "Excluir usuário?",
    "USER_DELETE_DIALOG_DESCRIPTION": "Esta ação é irreversível. Produtos e comunidades deste usuário serão transferidos para você e outros dados serão excluídos.",
    "USER_DELETE_DIALOG_MIGRATION_HEADING": "O que será transferido para sua conta",
    "USER_DELETE_DIALOG_MIGRATION_ITEM_PRODUCTS": "Produtos, aulas e páginas criados por este usuário serão reatribuídos a você.",
    "USER_DELETE_DIALOG_MIGRATION_ITEM_EMAIL": "Modelos de email, sequências e entregas criados por este usuário serão reatribuídos a você.",
    "USER_DELETE_DIALOG_MIGRATION_ITEM_AUDIENCE": "Ativos de audiência como segmentos, temas, planos de pagamento e sequências em andamento serão reatribuídos a você.",
    "USER_DELETE_DIALOG_MIGRATION_ITEM_COMMUNITY": "Funções de moderador e páginas de comunidade gerenciadas por este usuário serão reatribuídas a você.",
    "USER_DELETE_DIALOG_DELETION_HEADING": "O que será excluído",
    "USER_DELETE_DIALOG_DELETION_ITEM_COMMUNICATION": "Notificações, status de emails, avaliações de aulas, links de download, certificados e logs de atividade.",
    "USER_DELETE_DIALOG_DELETION_ITEM_COMMUNITY": "Posts, comentários, respostas, assinaturas, denúncias e curtidas da comunidade.",
    "USER_DELETE_DIALOG_DELETION_ITEM_COMMERCE": "Membros, faturas, matrículas em cursos e entradas de sequências de marketing.",
    "USER_DELETE_DIALOG_DELETION_ITEM_ACCOUNT": "A mídia do avatar e a conta do usuário.",
    "USER_DELETE_CONFIRMATION_LABEL": 'Digite "excluir" para confirmar',
    "USER_DELETE_CONFIRMATION_PLACEHOLDER": "Digite 'excluir' para confirmar",
    "USER_DELETE_CONFIRMATION_TOKEN": "excluir",
    "USER_DELETE_ACTION_LOADING": "Excluindo...",
    "APP_MESSAGE_USER_DELETED": "Usuário excluído",
    "APP_MESSAGE_USER_UPDATED": "Dados do usuário salvos",
    "USER_DETAILS_SAVE_BUTTON": "Salvar alterações",
    "USER_DETAILS_SAVE_BUTTON_LOADING": "Salvando...",
    "USER_NAME_PLACEHOLDER": "Digite o nome completo",
    "USER_EMAIL_PLACEHOLDER": "Digite o endereço de email",
    "PAGES_TABLE_HEADER_NAME": "Nome",
    "PAGES_TABLE_HEADER_ACTIONS": "Ações",
    "NEW_PAGE_NAME_PLC": "Minha página incrível",
    "NEW_PAGE_URL_LABEL": "URL",
    "NEW_PAGE_URL_PLC": "minha-pagina-incrivel",
    "DELETE_PAGE_POPUP_HEADER": "Excluir página?",
    "DELETE_PAGE_POPUP_TEXT": "Esta é uma ação irreversível e todos os dados relacionados a esta página serão excluídos.",
    "PAGE_TABLE_CONTEXT_MENU_DELETE": "Excluir",
    "APP_MESSAGE_PAGE_DELETED": "Página excluída",
    "APP_MESSAGE_MAIL_DELETED": "Email excluído",
    "NEW_PAGE_FORM_WARNING": "Estas configurações não podem ser alteradas depois, então prossiga com cuidado.",
    "DASHBOARD_PAGE_HEADER": "Bem-vindo",
    "UNNAMED_USER": "Visitante",
    "MAIL_REQUEST_FORM_REASON_FIELD": "Motivo",
    "MAIL_REQUEST_FORM_REASON_PLACEHOLDER": "Por favor, seja o mais detalhado possível. Isso nos ajudará a avaliar melhor sua solicitação.",
    "DASHBOARD_SELECT_HEADER": "Período",
    "DELETE_EMAIL_MENU": "Excluir",
    "DELETE_EMAIL_DIALOG_HEADER": "Excluir email",
    "OVERVIEW_HEADER": "Visão Geral",
    "HELP_HEADER": "Ajuda",
    "COMMUNITY_HEADER": "Comunidade",
    "COMMUNITY_MEMBERSHIP_LIST_HEADER": "Membros",
    "COMMUNITY_REPORTS_HEADER": "Conteúdo denunciado",
    "COMMUNITY_REPORTS_SUBHEADER": "Revise e gerencie conteúdo denunciado na sua comunidade",
    "COMMUNITY_MEMBERSHIP_LIST_SUBHEADER": "Revise e gerencie membros da sua comunidade",
    "SITE_SETTINGS_SECTION_COMMUNITIES": "Comunidades",
    "NEW_COMMUNITY_BUTTON": "Nova comunidade",
    "COMMUNITY_FIELD_NAME": "Nome da comunidade",
    "COMMUNITY_NEW_BTN_CAPTION": "Criar",
    "COMMUNITY_SETTINGS": "Gerenciar",
    "NEW_PAYMENT_PLAN_HEADER": "Novo Plano de Pagamento",
    "EDIT_PAYMENT_PLAN_HEADER": "Editar Plano de Pagamento",
    "PAYMENT_PLANS_HEADER": "Planos de Pagamento",
    "NEW_PAYMENT_PLAN_DESCRIPTION": "Configure um novo plano de pagamento para seu",
    "EDIT_PAYMENT_PLAN_DESCRIPTION": "Atualize a configuração de",
    "TOAST_TITLE_SUCCESS": "Sucesso",
    "TOAST_SEQUENCE_SAVED": "Alterações da sequência salvas com sucesso",
    "TOAST_QUIZ_PASS_MESSAGE": "Aprovado 🎉",
    "TOAST_QUIZ_FAIL_MESSAGE": "Reprovado ☠️",
    "TOAST_TITLE_ERROR": "Erro",
    "TOAST_DESCRIPTION_CHANGES_SAVED": "Alterações salvas",
    "DELETED_COMMENT_PLACEHOLDER": "Excluído",
    "SETTINGS_RESOURCE_PAYMENT": "Configurar pagamento",
    "SETTINGS_RESOURCE_API": "Documentação da API",
    "EDIT_CONTENT_MENU_ITEM": "Editar conteúdo",
    "PRODUCT_UNPUBLISHED_WARNING": "Este produto não está publicado. Não é visível para seu público.",
    "SEQUENCE_UNPUBLISHED_WARNING": "Esta sequência não está agendada para envio. Inicie-a para enviá-la ao seu público.",
    "PRODUCT_EMPTY_WARNING": "Seu produto está vazio. Adicione algum conteúdo para torná-lo mais interessante.",
    "BLOG_UPDATED_PREFIX": "Atualizado",
    "HEADER_HELP": "Ajuda",
    "CHECKOUT_PAGE_ORDER_SUMMARY": "Resumo do pedido",
    "TEXT_EDITOR_PLACEHOLDER": "Digite aqui...",
    "BTN_VIEW_CERTIFICATE": "Ver certificado",
    "GET_SET_UP": "Primeiros passos",
    "MANAGE_LINK_TEXT": "Gerenciar",
    "BLOG_LIST_EMPTY_TITLE": "Nenhum Post Encontrado",
    "BLOG_LIST_EMPTY_DESCRIPTION_PUBLIC": "A equipe ainda não publicou nenhum post.",
    "BLOG_LIST_EMPTY_DESCRIPTION_PRIVATE": "Você ainda não publicou nenhum post.",
    "PRODUCTS_LIST_EMPTY_TITLE": "Nenhum Produto Encontrado",
    "PRODUCTS_LIST_EMPTY_DESCRIPTION_PUBLIC": "A equipe ainda não adicionou nenhum produto.",
    "PRODUCTS_LIST_EMPTY_DESCRIPTION_PRIVATE": "Você ainda não adicionou nenhum produto.",
    "LOGIN_CODE_SENT_MESSAGE": "Enviamos uma senha de uso único para seu email.",
    "LESSON_EMBED_URL_LABEL": "Código de incorporação",
    "LESSON_CONTENT_LABEL": "Conteúdo",

    # ── config/strings.ts ──────────────────────────────────
    "error": "Erro",
    "domain_missing": "Domínio está faltando",
    "domain_doesnt_exist": "Domínio não existe",
    "domain_super_admin_email_missing": "Variável de ambiente SUPER_ADMIN_EMAIL não definida",
    "not_valid_subscription": "Nenhuma assinatura válida encontrada",
    "sign_in_mail_prefix": "Acesso a",
    "sign_in_mail_body": "Clique no link a seguir para fazer login.",
    "sign_in_link_text": "Fazer login",
    "past_date": "A data não pode ser no passado",
    "invalid_permission": "Permissão inválida",
    "user_not_found": "Usuário não encontrado.",
    "request_not_authenticated": "Requisição não autenticada",
    "content_cannot_be_null": "O conteúdo não pode estar vazio",
    "media_id_cannot_be_null": "A mídia não pode estar vazia",
    "item_not_found": "Item não encontrado",
    "drip_not_released": "Esta seção ainda não foi liberada para você",
    "not_a_creator": "Você não tem permissão para realizar esta ação",
    "course_not_empty": "Exclua todas as aulas antes de tentar excluir o curso",
    "invalid_offset": "Deslocamento inválido",
    "is_not_admin": "Privilégios insuficientes",
    "is_not_admin_or_creator": "Privilégios insuficientes",
    "blog_description_empty": "O campo descrição é obrigatório",
    "cannot_convert_to_blog": "O curso possui aulas, portanto não pode ser convertido em post",
    "cost_not_provided": "O campo valor é obrigatório",
    "invalid_cost": "Valor inválido",
    "cannot_add_to_blogs": "Não é possível adicionar aulas a um post de blog",
    "file_is_required": "Um arquivo é obrigatório",
    "error_in_moving_file": "Erro ao mover arquivo",
    "success": "sucesso",
    "user_name_cant_be_null": "O nome não pode ser nulo",
    "action_not_allowed": "Você não tem permissão para realizar esta ação",
    "invalid_input": "Entrada inválida",
    "payment_invalid_settings": "Configuração de pagamento inválida",
    "payment_info_required": "Adicione um método de pagamento antes de criar um plano pago",
    "unrecognised_currency_code": "Código de moeda não reconhecido",
    "only_admins_can_purchase": "Apenas administradores podem comprar cursos em nome de outros",
    "course_already_purchased": "Você já comprou este item",
    "payment_settings_invalid_suffix": "as configurações estão inválidas",
    "invalid_course_id": "ID do curso inválido",
    "invalid_user_id": "ID do usuário inválido",
    "payment_settings_invalid": "O método de pagamento não está configurado. Por favor, contate o administrador.",
    "not_enrolled": "Você não está matriculado no curso",
    "currency_iso_not_set": "O código ISO da moeda não está definido. Por favor, contate o administrador.",
    "payment_method_not_saved": "Configure um método de pagamento antes de definir sua chave secreta correspondente",
    "invalid_payment_method": "Método de pagamento inválido",
    "invalid_theme": "Tema inválido",
    "theme_not_installed": "O tema não está instalado",
    "invalid_layout": "Layout inválido",
    "missing_mandatory_blocks": "Blocos obrigatórios ausentes",
    "destination_dont_exist": "O destino não existe",
    "page_exists": "Uma página com esta URL já existe",
    "invalid_format": "Formato inválido",
    "no_thumbnail": "Nenhuma miniatura disponível",
    "file_size_exceeded": "Tamanho do arquivo excedido",
    "name_is_required": "O nome é obrigatório",
    "mimetype_is_required": "O tipo de mídia é obrigatório",
    "existing_group": "Um grupo com este nome já existe",
    "group_not_empty": "Esta seção possui aulas. Exclua-as antes de continuar",
    "update_payment_method": "Você precisa configurar um método de pagamento para criar conteúdo pago.",
    "currency_iso_code_required": "Código ISO da moeda é obrigatório. Exemplos: brl, usd, eur etc.",
    "currency_unit_required": "Um símbolo de moeda é obrigatório. Exemplos: R$, $, € etc.",
    "school_title_not_set": "Dê um título à sua escola antes de configurar as informações de pagamento.",
    "internal_error": "Ocorreu um erro interno. Por favor, tente novamente.",
    "presigned_url_failed": "Isso não funcionou! Volte e tente novamente.",
    "file_uploaded": "O arquivo foi enviado. Volte para ver sua mídia.",
    "media_deleted": "A mídia foi excluída. Volte para ver sua mídia.",
    "invalid_access_type": "O tipo de acesso pode ser público ou privado.",
    "answers_missing": "Respostas estão faltando.",
    "cannot_be_evaluated": "Esta aula não pode ser avaliada.",
    "need_to_pass": "Você precisa passar neste teste para marcá-lo como concluído.",
    "no_correct_answer": "Toda pergunta precisa ter pelo menos uma resposta correta.",
    "no_empty_option": "Opções sem texto não são permitidas nas perguntas.",
    "medialit_apikey_notfound": "Você precisa configurar o MediaLit para enviar arquivos.",
    "mail_already_sent": "O email já foi enviado",
    "mail_max_recipients_exceeded": "O número total de destinatários não pode exceder o limite",
    "invalid_mail": "Os campos Para, Assunto e Corpo são obrigatórios",
    "email_delivery_failed_for_all_recipients": "A entrega do email falhou para todos os destinatários",
    "courses_cannot_be_downloaded": "Um curso não pode ser oferecido como download.",
    "apikey_already_exists": "Chave de API com este nome já existe",
    "sequence_details_missing": "As seguintes configurações estão faltando",
    "invalid_emails_order": "Ordem de emails inválida",
    "no_published_emails": "Nenhum email publicado",
    "sequence_not_active": "Sequência não ativa",
    "sequence_already_started": "Sequência já iniciada",
    "mailing_address_too_short": "Endereço de correspondência muito curto",
    "mandatory_tags_missing": "Tags obrigatórias estão faltando",
    "cannot_delete_last_email": "Não é possível excluir o último email da sequência",
    "invalid_drip_email": "Email de gotejamento precisa de assunto e corpo",
    "cannot_invite_to_unpublished_product": "Não é possível convidar clientes para um produto não publicado",
    "rejection_reason_missing": "Motivo da rejeição está faltando",
    "joining_reason_missing": "Motivo da adesão obrigatório",
    "invalid_category": "Categoria inválida",
    "community_exists": "Uma comunidade com o mesmo nome já existe",
    "payment_plan_required": "Adicione um plano de pagamento antes de realizar esta ação",
    "community_requires_payment": "A comunidade requer pagamento",
    "community_has_no_payment_plans": "A comunidade não possui planos de pagamento",
    "duplicate_payment_plan": "Um plano de pagamento com o mesmo tipo já existe",
    "default_payment_plan_cannot_be_archived": "O plano de pagamento padrão não pode ser arquivado",
    "default_payment_plan_required": "Defina um plano de pagamento como padrão antes de ativar a comunidade",
    "community_content_already_reported": "Conteúdo já denunciado",
    "profile_incomplete": "Complete seu perfil para realizar esta ação",
    "cannot_reject_member_with_active_subscription": "Não é possível rejeitar um membro com assinatura ativa",
    "cannot_leave_community_last_moderator": "O último moderador não pode sair da comunidade",
    "cannot_delete_last_permission_user": "Não é possível excluir o último usuário com permissões necessárias:",
    "cannot_change_role_inactive_member": "Não é possível alterar a função de um membro inativo",
    "cannot_change_role_last_moderator": "Não é possível alterar a função do último moderador",
    "cannot_delete_last_category": "Não é possível excluir a última categoria",
    "lead_magnet_invalid_settings": "O produto deve ter exatamente um plano de pagamento gratuito para ativar o lead magnet",
    "certificate_invalid_settings": "O certificado só pode ser ativado para cursos",
    "sso_provider_already_exists": "Um provedor SSO com o mesmo ID já existe",
    "digital_download_no_files": "Este download digital está vazio. Por favor, contate o criador.",
    "download_link_expired": "O link de download expirou",
    "user_already_exists": "O usuário já existe",
    "unsubscribe_success": "Sentimos que você está saindo. Você foi removido da nossa lista de emails.",
    "download_course_cannot_have_groups": "Download digital não pode ter seções",
    "download_course_last_group_cannot_be_removed": "A última seção não pode ser removida de um download digital",
    "certificate_demo_course_id_required": "CourseID é obrigatório para certificado de demonstração",
    "provider_not_configured": "Configure o provedor antes de ativar",
    "provider_invalid_configuration": "Configuração do provedor inválida",
    "page_id_already_exists": "Este slug de URL já está em uso. Por favor, escolha um diferente.",

    # internal strings
    "error_unrecognised_payment_method": "Método de pagamento não reconhecido",
    "error_payment_method_not_implemented": "Ainda não implementado",
    "error_db_connection_failed": "Incapaz de estabelecer conexão com o banco de dados.",
    "error_env_var_undefined": "Uma variável de ambiente obrigatória não está definida",
    "app_running": "Servidor CourseLit está rodando em",
    "invalid_cloud_storage_settings": "Configurações de armazenamento em nuvem estão inválidas",
    "domain_not_specified": "Domínio não especificado",
    "default_group_name": "Primeira seção",
    "default_email_broadcast_subject": "Transmissão sem título",
    "default_email_sequence_subject": "Primeiro email",
    "default_email_sequence_name": "Sequência Sem Título",
    "joining_reason_creator": "Entrou como criador",
}


def extract_strings(filepath):
    """Extract exported string constants from a TypeScript file."""
    strings = {}
    with open(filepath, 'r') as f:
        content = f.read()
    
    # Match: export const NAME = "value";
    # Handle multi-line strings with concatenation
    pattern = r'export\s+const\s+(\w+)\s*=\s*(?:"([^"]*(?:\\.[^"]*)*)"|\'([^\']*(?:\\.[^\']*)*)\'|`([^`]*)`)'
    for match in re.finditer(pattern, content):
        name = match.group(1)
        value = match.group(2) or match.group(3) or match.group(4) or ""
        # Skip empty strings and non-translatable constants
        if value and not name.startswith("GENERIC_CURRENCY") and \
           not name.startswith("GENERIC_STRIPE") and \
           not name.startswith("GENERIC_PAYMENT") and \
           not name.startswith("GENERIC_CODE_INJECTION") and \
           not name.startswith("GENERIC_LOGO"):
            strings[name] = value
    
    # Also extract responses/internal object properties
    # Match: key: "value"
    obj_pattern = r'(\w+)\s*:\s*(?:"([^"]*(?:\\.[^"]*)*)"|\'([^\']*(?:\\.[^\']*)*)\')'
    for match in re.finditer(obj_pattern, content):
        name = match.group(1)
        value = match.group(2) or match.group(3) or ""
        if value and name not in strings:
            strings[name] = value
    
    return strings


def main():
    # Extract strings from both files
    ui_strings = extract_strings(UI_STRINGS)
    config_strings = extract_strings(CONFIG_STRINGS)
    
    # Merge all strings
    all_strings = {}
    
    # ui-config strings (with "ui." prefix namespace)
    en_ui = {}
    pt_ui = {}
    for key, value in ui_strings.items():
        en_ui[key] = value
        pt_ui[key] = PT_BR_TRANSLATIONS.get(key, value)  # fallback to English
    
    # config strings (with "api." prefix namespace)
    en_api = {}
    pt_api = {}
    for key, value in config_strings.items():
        en_api[key] = value
        pt_api[key] = PT_BR_TRANSLATIONS.get(key, value)  # fallback to English
    
    # Email templates
    en_email = {
        "magic_code_body": "{code} is your verification code.",
        "magic_code_important": "IMPORTANT:",
        "magic_code_warning": "Do not share this email with anyone as anyone can log in to your account using the link in this email.",
        "course_enroll_body": "You have been enrolled in a course:",
        "course_enroll_access": "To access all of your content,",
        "course_enroll_login": "log in",
        "course_enroll_here": "here.",
        "download_thanks": "Thank you for signing up for {courseName}.",
        "download_button": "Download now",
        "download_best": "Best,",
        "powered_by": "Powered by",
    }
    pt_email = {
        "magic_code_body": "{code} é seu código de verificação.",
        "magic_code_important": "IMPORTANTE:",
        "magic_code_warning": "Não compartilhe este e-mail com ninguém, pois qualquer pessoa pode fazer login na sua conta usando o código neste e-mail.",
        "course_enroll_body": "Você foi matriculado em um curso:",
        "course_enroll_access": "Para acessar todo o seu conteúdo,",
        "course_enroll_login": "faça login",
        "course_enroll_here": "aqui.",
        "download_thanks": "Obrigado por se inscrever em {courseName}.",
        "download_button": "Baixar agora",
        "download_best": "Atenciosamente,",
        "powered_by": "Desenvolvido por",
    }
    
    # Write EN messages
    en_messages = {"ui": en_ui, "api": en_api, "email": en_email}
    pt_messages = {"ui": pt_ui, "api": pt_api, "email": pt_email}
    
    os.makedirs(os.path.join(MESSAGES_DIR, "en"), exist_ok=True)
    os.makedirs(os.path.join(MESSAGES_DIR, "pt-BR"), exist_ok=True)
    
    with open(os.path.join(MESSAGES_DIR, "en", "messages.json"), 'w', encoding='utf-8') as f:
        json.dump(en_messages, f, indent=2, ensure_ascii=False)
    
    with open(os.path.join(MESSAGES_DIR, "pt-BR", "messages.json"), 'w', encoding='utf-8') as f:
        json.dump(pt_messages, f, indent=2, ensure_ascii=False)
    
    # Stats
    total_en = len(en_ui) + len(en_api) + len(en_email)
    translated = sum(1 for k in list(en_ui.keys()) + list(en_api.keys()) if k in PT_BR_TRANSLATIONS)
    untranslated_keys = [k for k in list(en_ui.keys()) + list(en_api.keys()) if k not in PT_BR_TRANSLATIONS]
    
    print(f"Total strings extracted: {total_en}")
    print(f"  UI strings: {len(en_ui)}")
    print(f"  API strings: {len(en_api)}")
    print(f"  Email strings: {len(en_email)}")
    print(f"Translated to pt-BR: {translated}")
    print(f"Untranslated (using English fallback): {len(untranslated_keys)}")
    if untranslated_keys:
        print(f"\nUntranslated keys:")
        for k in untranslated_keys[:20]:
            print(f"  - {k}")
        if len(untranslated_keys) > 20:
            print(f"  ... and {len(untranslated_keys) - 20} more")


if __name__ == "__main__":
    main()
